---
- hosts: local
  become: yes

  tasks:
    - name: Stopping MariaDB
      service:
        name: mysql
        state: stopped

    - name: Adding MariaDB conf
      copy:
        remote_src: true
        src: "/root/mariadb_{{instance_name}}.cnf"
        dest: /etc/mysql/conf.d/mariadb.cnf

    - name: Chmoding format script
      file:
        path: /root/format
        state: file
        mode: a+x

    - name: Making mount folder
      file:
        path: /srv/icehrm
        state: directory

    - name: Formatting volume
      shell: /root/format

    - name: Mounting volume
      mount:
        src: /dev/vdb
        name: /srv/icehrm
        fstype: ext4
        state: mounted

    - name: Making some folders
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - /srv/icehrm/data
        - /srv/icehrm/mysql

    - name: Copying MySQL files
      synchronize:
        src: /var/lib/mysql/
        dest: /srv/icehrm/mysql/
        recursive: yes
        perms: yes

    - name: Removing old MySQL files
      file:
        path: /var/lib/mysql
        state: absent

    - name: Mounting MySQL folder
      mount:
        opts: bind
        fstype: none
        src: /srv/icehrm/mysql
        name: /var/lib/mysql
        state: mounted

    - name: Adding mounting at boot
      lineinfile:
        dest: /etc/fstab
        line: "/dev/vdb   /srv/icehrm   ext4   defaults   0   0"

    - name: Adding boot script
      copy:
        remote_src: true
        src: /root/rc.local
        dest: /etc/rc.local

    - name: Adding Galera boot script
      copy:
        remote_src: true
        src: /root/testmysql
        dest: /opt/testmysql

    - name: Chmoding Galera boot script
      file:
        path: /opt/testmysql
        state: file
        mode: a+x

    - name: Disabling MySQL at  boot
      service:
        name: mysql
        enabled: no

    - name: Including customs tasks
      include: "/root/config_{{instance_name}}.yml"
      vars:
        sqlpass: "{{sqlpass}}"

    - name: Removing any Apache2 content
      shell: rm -rf /var/www/html/*

    - name: Creating GlusterFS client directory
      file:
        path: /var/www/html/app
        state: directory

    - name: Waiting for inst1 to continue
      wait_for:
         host: inst1
         port: 49152
         delay: 1
         timeout: 300

    - name: Mounting GlusterFS client
      shell: mount -t glusterfs inst1:/gfscluster_icehrm /var/www/html/app

    - name: Extracting iceHRM's zip file
      unarchive:
        src: /root/icehrm.zip
        dest: /root/
        remote_src: yes

    - name: Moving iceHRM's files in the right folder
      shell: cp -R /root/icehrm_v18.0.OS/* /var/www/html/ && rm /root/icehrm.zip && rm -rf /root/icehrm_v18.0.OS

    - name: Changing owner of iceHRM's files
      file:
        path: /var/www/html/
        owner: www-data
        group: www-data
        recurse: yes