---
- name: Fixing boot script
  lineinfile:
    dest: /etc/rc.local
    regexp: "^/opt/testmysql INSTANCE_NAME"
    line: "/opt/testmysql inst1"

- name: Waiting for inst1 to continue
  wait_for:
     host: inst1
     port: 4567
     delay: 1
     timeout: 300

- name: Starting MariaDB
  service:
    name: mysql
    state: started