#!/bin/bash

sed "/wsrep_cluster_address/d" /etc/mysql/conf.d/mariadb.cnf > /etc/mysql/conf.d/mariadbcnf
rm /etc/mysql/conf.d/mariadb.cnf
mv /etc/mysql/conf.d/mariadbcnf /etc/mysql/conf.d/mariadb.cnf

if nc -z $1 4567
then
        echo -e "wsrep_cluster_address=\"gcomm://inst1,inst2\"" >> /etc/mysql/conf.d/mariadb.cnf
        /etc/init.d/mysql start
else
        echo -e "wsrep_cluster_address=\"gcomm://\"" >> /etc/mysql/conf.d/mariadb.cnf
        /etc/init.d/mysql start --wsrep-new-cluster
fi