#!/bin/bash

CRON_FILE="/etc/cron.d/dup_backup"
CRON_SCRIPT_DIR="/etc/duplicity/cron_scripts"
BACKUP_SCRIPT="/etc/duplicity/to_swift.sh"
SETTINGS_JSON_PATH=$1

if [ ! "$SETTINGS_JSON_PATH" ]; then
    echo "SETTINGS_JSON_PATH is mandatory."
    echo -e """\
\e[32mUSAGE:\e[0m ./dup_configure.sh SETTINGS_JSON_PATH

Configures Duplicity cron jobs for automated backup.
"""
    exit 1
fi

if [ ! -r "$SETTINGS_JSON_PATH" ]; then
  echo "ERROR: Settings JSON file passed as parameter does not exist or cannot be read.";
  exit 1;
fi

SETTINGS_JSON=`cat $SETTINGS_JSON_PATH`

mkdir -p "$CRON_SCRIPT_DIR"

echo "Rewriting crontab file $CRON_FILE"
echo """\
# Crontab for server backup jobs
# Generated by Backup Bundle scripts
# Written by the CAT (Cloudwatt Automation Team)
""" > "$CRON_FILE"

TIMESLOTS=`jq ". | keys | .[]" <<< "$SETTINGS_JSON" | tr -d '"'`

for TIMESLOT in "$TIMESLOTS" ; do
  echo " - Preparing cron for timeslot \"${TIMESLOT}\""

  CRON_SCRIPT=`echo "$TIMESLOT" | tr " " "_"`
  CRON_SCRIPT="${CRON_SCRIPT_DIR}/${CRON_SCRIPT}.sh"
  echo "   + Writing command to crontab file:"
  echo "     $TIMESLOT root $CRON_SCRIPT"
  echo "$TIMESLOT root $CRON_SCRIPT" >> "$CRON_FILE"

  echo "   + Writing cron executable"
  echo "     # Cron executable for timeslot \"${TIMESLOT}\""
  echo "# Cron executable for timeslot \"${TIMESLOT}\"" > "$CRON_SCRIPT"
  TIMESLOT_JSON=`jq ".[\"${TIMESLOT}\"]" <<< "$SETTINGS_JSON"`
  JSON_COUNT=`jq ". | length" <<< "$TIMESLOT_JSON"`
  for DUP_INDEX in `seq -f "%02g" 0 "$JSON_COUNT" | head -n "$JSON_COUNT"`; do
    echo "     sudo bash $BACKUP_SCRIPT $(jq -c ".[$DUP_INDEX]" <<< "$TIMESLOT_JSON")"
    echo "sudo bash $BACKUP_SCRIPT $(jq -c ".[$DUP_INDEX]" <<< "$TIMESLOT_JSON")" >> "$CRON_SCRIPT"
  done
done
