---
# Handler for reprequirement

- name: server restart
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  become: yes
  become_method: sudo

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started port=22 delay=15 timeout=300 connect_timeout=15

- name: ntp restart
  service: name=ntpd state=restarted
  become: yes
  become_method: sudo

- name: mongod restart
  service: name=mongod state=restarted
  become: yes
  become_method: sudo

- name: waiting for mongod to come back
  wait_for: host={{ inventory_hostname }} state=started port={{ monconf_port }} delay=10 timeout=300 connect_timeout=10
  become: yes

