---
- name: Cron upate ClamAV
  cron:
   name="update ClamAV"
   minute="00"
   hour="1"
   user="root"
   job="/usr/bin/freshclam"

- name: add daily scan clamav
  template: src=dailyclamscan.j2 dest=/etc/cron.daily/dailyclamscan mode=700
  notify: restart clamav-daemon


- name: enabled spamassassin /etc/default/spamassassin pt 1
  lineinfile: dest=/etc/default/spamassassin regexp='^ENABLED=0' line='ENABLED=1' backrefs=yes
  notify: restart spamassassin

- name: enabled spamassassin /etc/default/spamassassin pt 2
  lineinfile: dest=/etc/default/spamassassin regexp='^CRON=0' line='CRON=1' backrefs=yes
  notify: restart spamassassin


- name: Copying local.cf spamassassin
  copy: src=local.cf dest=/etc/mail/spamassassin/local.cf
  notify: restart spamassassin

- name: Create the spamd user
  user: name=spamd shell=/bin/false home=/var/log/spamassassin


- name: Cron update spam 1
  cron:
   name="update spam 1"
   minute="20"
   hour="02"
   user="root"
   job="/usr/bin/sa-update"

- name: Cron update spam learn 1
  cron:
   name="update spam learn 1"
   minute="30"
   hour="02"
   user="root"
   job="usr/bin/sa-learn --ham /var/vmail/{{mail_domain}}/*/{cur,new,.*}"


- name: Cron update spam learn 2
  cron:
   name="update spam learn 2"
   minute="40"
   hour="02"
   user="root"
   job="/usr/bin/sa-learn --spam /var/vmail/{{mail_domain}}/*/.Spam/{cur,new}"