---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: all
  become: yes

  tasks:
    - apt: update_cache=true upgrade=full
      when: "'slaves' in group_names"

    - name: install packages
      apt: pkg={{ item }} state=present
      with_items:
        - zabbix-agent
        - ntp
      notify: restart ntp
      when: "'slaves' in group_names"

    - name: get zabbix_server IP
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp=".*Server=.*"
        line="Server={{ hostvars['127.0.0.1'].ansible_default_ipv4.address }}"
      when: "'slaves' in group_names"

    - name: zabbix slave hostname
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp="^Hostname="
        line="Hostname={{ ansible_hostname }}"
      notify: restart zabbix
      when: "'slaves' in group_names"

  handlers:
    - name: restart ntp
      service:
        name=ntp
        state=restarted
        enabled=yes

    - name: restart zabbix
      service:
        name=zabbix-agent
        state=restarted
        enabled=yes
