#!/bin/sh

. ../env.sh
. ../functions.sh

echo "-> ssh_vm_execute_cmd $PRIVATE_KEY \"$SSH_USER@$IP\" \"ps aux | grep haveged\""
out=$(ssh_vm_execute_cmd $PRIVATE_KEY "$SSH_USER@$IP" "ps aux | grep haveged")
echo "$out"

[ "`echo $out | grep sbin/haveged`" ]
