---
- name: "Download postfixadmin"
  get_url: >
    url=http://sourceforge.net/projects/postfixadmin/files/latest/download
    dest=/tmp/postfixadmin-latest.tar.gz
    force=yes
    timeout=40

- name: "Prepare - create Path"
  file:
    dest: "/usr/share/roundcube/postfixadmin"
    state: directory
    recurse: yes
    mode: 775

- name: "Untar postfixadmin"
  shell: "tar -C /usr/share/roundcube/postfixadmin --strip-components=1 -xvf /tmp/postfixadmin-latest.tar.gz"
  args:
    creates: "/usr/share/roundcube/postfixadmin/index.php"

- name: add permission
  shell: "chown -R root:root /usr/share/roundcube/postfixadmin && chmod -R 777 /usr/share/roundcube/postfixadmin"

- name: "Configure postfixadmin"
  template: src=config.inc.php.j2 dest=/usr/share/roundcube/postfixadmin/config.inc.php

- name: enable imap
  shell: /usr/sbin/phpenmod imap

- name: restart apache
  service: name=apache2 state=restarted

- name: setup postfixadmin
  shell: curl http://localhost/postfixadmin/setup.php