---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  become: yes

  vars:
    package: zabbix
    service_username: "admin"
    service_password: "zabbix"
    server_ip: 10.0.7.100
  tasks:

    - name: update apt
      apt: update_cache=true upgrade=full
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")


    - name: Set timezone variables Debian
      copy: content='Europe/Paris'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      when: ansible_os_family == 'Debian'


    - name: update timezone debian
      shell: dpkg-reconfigure --frontend noninteractive tzdata
      when: ansible_os_family == 'Debian'

    - name: change time zone Redhat
      shell: timedatectl set-timezone 'Europe/Paris'
      when: ansible_os_family == 'RedHat'


    - name: Add repository for CentOS 7
      yum:
        name=http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-agent-3.2.0-1.el7.x86_64.rpm
        state=present
      when: ansible_distribution == "CentOS" and ansible_distribution_version.split(".")[0] == "7"

    - name: Add repository for CentOS 6
      yum:
        name=http://repo.zabbix.com/zabbix/3.2/rhel/6/x86_64/zabbix-agent-3.2.0-1.el6.x86_64.rpm
        state=present
      when: ansible_distribution == "CentOS" and ansible_distribution_version.split(".")[0] == "6"

    - name: repo Ubuntu xenial
      apt: deb=http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix/zabbix-agent_3.2.0-1+xenial_amd64.deb
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

    - name: repo Ubuntu trusty
      apt: deb=http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix/zabbix-agent_3.2.0-1+trusty_amd64.deb
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

    - name: repo Debian jessie
      apt: deb=http://repo.zabbix.com/zabbix/3.2/debian/pool/main/z/zabbix/zabbix-agent_3.2.0-1+jessie_amd64.deb
      when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'

    - name: repo Debian wheezy
      apt: deb=http://repo.zabbix.com/zabbix/3.2/debian/pool/main/z/zabbix/zabbix-agent_3.2.0-1+wheezy_amd64.deb
      when: ansible_distribution == 'Debian' and ansible_distribution_release == 'wheezy'


    - name: set ServerActive IP
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp=".*ServerActive=.*"
        line="ServerActive={{ server_ip }}"
      notify: restart zabbix

    - name: set Server IP
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp=".*Server=.*"
        line="Server={{ server_ip }}"
      notify: restart zabbix



    - name: zabbix agent hostname
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp="^Hostname="
        line="Hostname= {{ ansible_hostname }}"
      notify: restart zabbix


    - name: set selinux permissions
      selinux: policy=zabbix_agent_t state=permissive
      when: ansible_distribution == "CentOS"

    - name: register zabbix agent
      local_action:
          module: zabbix_host
          server_url: "http://{{ server_ip }}"
          login_user: "{{ service_username }}"
          login_password: "{{ service_password }}"
          host_name: "{{ ansible_hostname }}"
          link_templates:
            - Template OS Linux
          host_groups:
            - Linux servers
          status: enabled
          state: present
          interfaces:
            - type: 1
              main: 1
              useip: 1
              ip: "{{ ansible_default_ipv4.address }}"
              dns: "{{ ansible_hostname }}"
              port: 10050

  handlers:
    - name: restart zabbix
      service:
        name=zabbix-agent
        state=restarted
        enabled=yes

