---

- name: creating mailserver MySQL database
  mysql_db: name=mailserver state=present

- name: creating MySQL user to read the mailserver database
  mysql_user: name=mailuser password={{ mysql_mailuser_password }} priv=mailserver.*:ALL state=present


- name: copying MySQL database schema to server
  copy: src=schema.sql dest=/tmp

- name: setting up SQL schema of mailserver database
  mysql_db: name=mailserver state=import target=/tmp/schema.sql

- name: copying MySQL test data to server
  template: src=add-admin.sql.j2 dest=/tmp/add-admin.sql

- name: populating the database with test data
  mysql_db: name=mailserver state=import target=/tmp/add-admin.sql

