#!/bin/sh
#Script generated by packit.perl on Fri Jun 19 16:46:31 2015.

if [ -z "$UNPACK_ONLY" -a "`id -u`" != 0 ] ; then
  echo "This script needs to be run with root privileges.  Please try:"
  echo "  sudo -H sh $0"
  exit 1
fi
export HOME="`getent passwd 0 | cut -d: -f6`"
cd "`mktemp -d || echo /dev/null`"
if [ "$?" != 0 ] ; then
  echo "Unable to change to temporary directory; cannot continue."
  exit 2
fi
echo "Working in `pwd`..."
#Add hook to ensure the payload runs after successful unpacking
nexit() {
if [ "$1" = "0" ] ; then
 do_md5_check || { echo "Checksum fail." ; exit 1 ; }
 if [ -n "$UNPACK_ONLY" ] ; then
  echo "Unpack complete in `pwd`. Exiting."
 else
  chmod +x upgrade_to_8.sh
  sed -i 's/read -p "Press any key to continue..." -n1//g' upgrade_to_8.sh
#  sed 31s/.*//  upgrade_to_8.sh
  sed "244cma if grep '^deb.* universe$' /etc/apt/sources.list && " upgrade_to_8.sh
  sed "245cma grep '^deb.*multiverse$' /etc/apt/sources.list ; then" upgrade_to_8.sh
  sed "170cma apt-get -y --force-yes install software-properties-common" upgrade_to_8.sh
  sed "196cma apt-add-repository -y --force-yes ppa:nebc/bio-linux" upgrade_to_8.sh
  sed "197cma apt-add-repository -y --force-yes ppa:marutter/c2d4u" upgrade_to_8.sh
  sed "198cma apt-add-repository -y --force-yes ppa:x2go/stable" upgrade_to_8.sh
  sed "258cma apt-get -y --force-yes update" upgrade_to_8.sh
#  sed "308cma apt-get -y --force-yes autoremove" upgrade_to_8.sh
  sed "314cma apt-get -y --force-yes install virtualbox-guest-{dkms,source,utils,x11}" upgrade_to_8.sh
  
  echo 'Unpack phase complete.  Running upgrade_to_8.sh' ; echo '====>>>'
  exec ./upgrade_to_8.sh <&1
 fi
else \exit "$@"
fi }
alias exit=nexit
#Always prefer Perl for uudecoding
uudecode() {
 if which perl >/dev/null ; then
  read l0 l1 l2
  perl -ne 'print unpack("u*",$_)' >$l2 &&
  chmod $l1 $l2
 else
  uudecode "$@"
 fi
}
#No extra md5sum checking
do_md5_check() {
  true
}
#!/bin/sh
# This is a shell archive (produced by GNU sharutils 4.14).
# To extract the files from this archive, save it to some FILE, remove
# everything before the '#!/bin/sh' line above, then type 'sh FILE'.
#
lock_dir=_sh09863
# Made on 2015-06-19 16:46 BST by <tbooth@balisaur>.
# Source directory was '/home/tbooth/sandbox/bl8_things'.
#
# Existing files WILL be overwritten.
#
# This shar contains:
# length mode       name
# ------ ---------- ------------------------------------------
#   8990 -rw-rw-r-- bio-linux-keyring.deb
#   5490 -rwxrw-r-- pick_cran_mirror.py
#   3125 -rw-r--r-- sources.list.clean
#   2212 -rwxrwxr-x bl_install_master_list.sh
#  13459 -rwxrwxr-x upgrade_to_8.sh
#    725 -rw-rw-r-- pseudo_orphans.txt
#   4851 -rwxrwxr-x bl_master_package_list.txt
#   1746 -rw-rw-r-- message1.txt
#
MD5SUM=${MD5SUM-md5sum}
f=`${MD5SUM} --version | egrep '^md5sum .*(core|text)utils'`
test -n "${f}" && md5check=true || md5check=false
${md5check} || \
  echo 'Note: not verifying md5sums.  Consider installing GNU coreutils.'
if test "X$1" = "X-c"
then keep_file=''
else keep_file=true
fi
echo=echo
save_IFS="${IFS}"
IFS="${IFS}:"
gettext_dir=
locale_dir=
set_echo=false

for dir in $PATH
do
  if test -f $dir/gettext \
     && ($dir/gettext --version >/dev/null 2>&1)
  then
    case `$dir/gettext --version 2>&1 | sed 1q` in
      *GNU*) gettext_dir=$dir
      set_echo=true
      break ;;
    esac
  fi
done

if ${set_echo}
then
  set_echo=false
  for dir in $PATH
  do
    if test -f $dir/shar \
       && ($dir/shar --print-text-domain-dir >/dev/null 2>&1)
    then
      locale_dir=`$dir/shar --print-text-domain-dir`
      set_echo=true
      break
    fi
  done

  if ${set_echo}
  then
    TEXTDOMAINDIR=$locale_dir
    export TEXTDOMAINDIR
    TEXTDOMAIN=sharutils
    export TEXTDOMAIN
    echo="$gettext_dir/gettext -s"
  fi
fi
IFS="$save_IFS"
if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null
then if (echo -n test; echo 1,2,3) | grep n >/dev/null
     then shar_n= shar_c='
'
     else shar_n=-n shar_c= ; fi
else shar_n= shar_c='\c' ; fi
if test ! -d ${lock_dir} ; then :
else ${echo} "lock directory ${lock_dir} exists"
     exit 1
fi
if mkdir ${lock_dir}
then ${echo} "x - created lock directory ${lock_dir}."
else ${echo} "x - failed to create lock directory ${lock_dir}."
     exit 1
fi
# ============= bio-linux-keyring.deb ==============
${echo} "x - extracting bio-linux-keyring.deb gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh09863/gzi
M'XL("+RNC%,"`V)I;RUL:6YU>"UK97ER:6YG+F1E8@"-<U5,'`"[+%K<W:VX
MN[L5BKL6=X?%?8'B[N[%H<6++>[N%'=WM]USSL-_7NY-[IU,OF0FF8=)YJ,2
M,7.WL!5#MK0RMS-S9C6W<S9S]Z6DI.3DX>#DYQ+@Y^"@I/QO4O[G<G)P\/'P
M4%+R4/X'ILA<;!S(%B[.`'<71S:`F3N;C=__.\_'S_._>8I81*C_`0SL98:Q
MRP('[D^/?!.W7\:_%;[_*U,01H:9;]FS5L*C_!K>[HK#_R?G7_+E;^5_B<<"
MYU]('!VQR:2$$A?IA$Q\R6H:2)ZZZA;DY>S^&2>OKUR)Q2",4<;(WW+TO=CB
MEI.7;>',$D_PA%2D-SXO?3)""K&?B*UJDX;!39\CQJKU3^*7]+`-%+)V(C=%
MJN\@3R]O/Q0J_U_`D/<>O7X"Q.FB%>+-(7V+,#SQR`;V7AVCMY`+%=\I5F]H
M-4_HK.L]W1;X!K,,Y28!HJ?=/9A:9[>'R^FQVUG/_@(M_.F_FVL@EE=?15P*
ME8*1U--?PLPQ]4OEF8J=6/SDDQS;C/QX"UV15*R6=JY43)41CC-`90:6W+N,
M1B5\@>N;Y'MT6!I%WV>9BGG&@AGNU:9T^XGJW(14V*G;3/K:^7:=(;1EI`\-
M>T@R\:([HWO?69'=*AF7GI-6Q>%)H-==T:W0*&^JY#KNI+O'S-D6D_:R2/A,
M]9!5.[(%?Q\LZJA-^]_JP&XDR;J>70U.;+%O<FN>GT^T[!'76,%]$`_:.IW'
MC!F(6<J&+[CB]/&U4.ZS^!XBB9L,$8?WR&C0&QNYB55X*VSGDQKC1/W$$&G;
MO#3(VBAT*&[^?6R!>2YG-U'VR)VOVV^N7^-&6.,`(<.9WXL\YPS`=<C:0:G=
ML1HZ_[5C_2AW)TMNSH>A3]Y:HPM.RS6*/;J3O/=2C^UJ>CO2V&O)5E$[_:/I
ME_]J5BXV62:)-*V2'6%5\T?:!(]X-#L<'N$Y&('W#D8EHLD*I4)).);SY'NV
MQW?`5X_]WZ<JG?%+_6..[G`CM>F^2[_[U]ZA.0`RQPT(0=Z=G%VEBC6\&&,U
MB$#*_X.K0MO0;JX>TE`,4%"69@"S_YWV_\=W"'!R<?]?UMVIFWAA[T6K-_.!
M]^SV)93);R6$_"1L:YT_19+@`;5CIX&BP*.FK'Y=5$.:.T6Q=TV"&H=(Z>+C
MZ9]U';O7!_S'0G"[9%NR`/C^W2GX`WQO0TB-B4W_#0YXO9WZ50E\RO^A"D%J
M#5P&O%ZVB;/NMX,=9CX-&R#\+:"0=1MH2/(-J#",BG0H:!=2&`FI4,F$^8CL
MI9!U_C"#H?T?+S[8,"#3NE)L)Q@>C!A3S`&#!>>WGVC^T@"&F$0&+\<%7^68
M"4-$,JQ2^>V>C^T4(1K*2R"28)@!\/9-Y&[GD5E6N-J#/#IF,!`3,2Q9_//+
M9S]$?`/\,:`GF1*_S3+V-G6GKWP4I!GQPJ_#+?AX/"&AQE)H30H><9G_K3_O
M(OQ!<,'.\;`.H242J_P<38600/D187?E$RPJ8A(^^CO2`HR3:>YAZ]+1M=(4
M4H)BG?/@:GV5[Z'?.0Z\+[$T>-ZXJ&%6DR<RCL>4V*CZJ;76PZD7%83ZMPI>
MY\F2$J+RI-T$VW8GA@D[S'"H*&A\?E#(<@<RAN"LH?J;4EMTBDW]A+Z<\C/6
M4PL54VBUI<XU4W5"^<OQMRP^$%NKVGF?7H%0QY1(#@B%)'2N&P5:H#>D)W5X
M!ZK1BGZFPQLU&W8CEQ5-[WVQT,^W8OIEYC14!O"W/L.8T:&`W\G*LZD6V"'4
MWZU.I-3AFEEU=PN6Q1NHS!OH_XS*IJ(2XE1]0D44-*:O\!PWOI0\A$HNW9#Q
M`O!6$D$DTE;??E)0M5'K(CS'5U%J>"2J3FCBU!9[H;PM2>;_S)!JYG#7+X<1
M4.C+LPKHQ0^CYC7PC='9"\..Z5ZS`PZ][,5TDO;MI+X7X(][7H-#'V!O/Y5^
MI2+RNK;3X1@8A8EL5U9.7,;5=ZXGY1^0NOQ^JPB&`4?'9Y&_9!,`^R#,"O<5
M)D_;(`CD41=RM0P)GH>HX[[-0=3A:*^>$C<_*>C<<#^7()#B=_';R">7[VC,
MM1D#0^@3KK'<&&#?M]4!CLPYQJPM'31F5"E:OYMQ71*<-CM-.0-?A>B<-ZG0
M.`IK,8NDQ<I[TX2B*-*"FA[W'Q17#696*+92:1[ZYY*]V;_,Z(>-7M%)K)_[
MPL!X4!A>8^L:DJW<?5D$)+P&JV*K;Z+'ARVXTK06YFR;\<&D.FYD2Z2Q7KNS
MP[H!KDL[W]"@.C"&+-+,$L_+Y]]%:>KJQMQ#D\67@@")>J0RVYBH/J\R]B.+
M0T]2HI\6U+;<)VG?8#C"@(A_4TL6.>3!>5X],<)2]9M!1I$LF[L/P`XJYM<U
M@E\(7+GR7\2>/>J[2O6'R!#\D/U+$@J_Z[D1F#$EH963-.]?VJ@"'+O3*&G>
MKZ/M&@D>0FI"!Q;8<Y`9"A!-6DQC21C*0:77+_B[K"TP_9=B@$)ORL,CFQ^K
M1H&Q;JR\&,!';5^_YH:1TR+HN6[`5<"T.JI(6;:<P_O4*/I7]!>2)7&,,WNM
MP9>]Y:(N$#55!$8YBEJT-\JE)SQAG;?LSYX/LO<03C54JPN))X=RRN<)I-7,
M%80W`2GUG:S$8[1D<*`#Y2">^<_B<5J0@OS#OY`F4&UA^![RJ-%4.56+GT9;
M=TDU%_%3E+1%](`NO7@\H^0-X_D]DRR,D2<14SI0E4WP6<TPNQ:#F!*\9_A3
MQY#T;)WY0X0X&BO\WFN&DWH!/*FF(@2(%C;(%@4D6`4F6#P$DR_W@I0<KO)2
MGAGB<COEV0O4#;RJ*P6H9\C]XW]4'U`5$&IH=0*F7<LU947JZC%#Q`=5^2\P
M!`;)2DO3%0-WGB_P-_R52%AHN._>::M6,G4)&YUF:^R;9GE%BXL70][=54U=
M&YS3"WO0S*(>?+U;^)[6P+*C;JW<5K;\A6>:P_LV=LM*"X_6Y095?=D9L8C6
MN*U0<9^5XW_8S/;^-HW$?/[BKIBMB8ZX83;R]5!3<.HIJ]+D9$-SD0-UT0-#
M;+JE\6SEH'PCR;J0I%L?`MKJ:O,5YU3B2C3#"JC%;'4WN#)==5N\RUC&E$R'
MPD4-.C>F]NY<@F"^A7H?'N0U\9<0.13Z/.\ZI+TD+;2?:3S5'F'1?`G<%+&S
MG+&09+(B>P$L\/["0^^"<<0/ZRK;M&#6'OR45/'$$<G7J&(Q`"0KEVCC\F*O
M2A)E)[K5_[:CFC++-T.'H+L*0`66JM>:_7R!!=Y)`A3=/%!NG7)'5N:^I&F/
M=@3N^S[J(]_ZD\JW1>8#@S95-LV#_'E#MA,S]ZG@S,C!6HZZ_W[#UHXZ9X,R
M-KFM'C\Y.&RNPG+473="8N:"]R:,ES"W7QQ<8=!Y1@N17NO)YW%-@O8S2SXM
M+P$;10]"\2FV+RKD;VDDTG$S+:JOO):B4G0U<\TF<\1JHX1SCA0H8K*)5`#+
M2[=@]<@<R="2R$?!Y<1;0?N9<+=M9<PO/QC3UL4,N`I#ZS&E)3!]*Q_@OO]>
MAC%+IFSD.G(;D.7`F&^G%_`\6Q8A3=H2P;#TZ_E-UO/0HAA/(WO)BA:Z];>C
MB#;O.@TCQO<@EV"\WFD$R,J==^DAKIF3S`T.KLJ<B53G0$;4D9(;-3J38V,)
MN&\\F[GO#,Y_-N8@JKY=X#Y"L^,^T:+M7KC!'@A+W6GWM1:L'&0O>#7IAU2[
MU7;LS13^(@:+IX*"4R%]B(HID(5/C*<P2!_F1RSDT^(\^"58'JJ4)BP(4V)K
M2W-P]I>`4$W;G'4NO%T8+_)<H\+G5E$R6Z%+'P'_V`[+I&\8X^Q55`C"U)C!
M3<$Z]35#(E)!:PY7``-V7GU!SQCVR<HA<)HY(+`T!=<UD]B&YBU.)`#Z<&LB
M\><T9G$0%ZI2S9(DGY7$I5],W>7M:;C8<TZI8.75N3<BWG+6;XTKWTVXWWL>
M7QA0['X@+#;>9/G>JJU;L.'C=?0R7#MGU\W]PZJ"ZVOI^DEX"V)S>FT:U?_7
MA-T"!/+UUEL-CFPSWSYIPS(7GK8*#T8$(6>^+KI^=/<@513$,%1BC4P-4'=8
MQ$?4WXW)T(RPP+:3"!],QX^T4`W0FTP-)-:7BNU:[V]/,\^AX,?=ZHM]!9RK
MW]CVC:RAS'PJBPM>H_?`)VG!<5(>3!GGTZ`+(QZ&9<^XKE2I?K?+I`Y+?A!;
M-68MW9LKGM@1^L;,T0GH=FL#4D/%OLW7<)1WVAP+?UR)8C]=-^IQZC6]Z:F+
MKT?KJ,D%LK^S*'W)==2V"N#I(__NJ1"()&*"0+_;L4N%2IXOHG?3$/DS?1I)
ME/M/^F6RG2E\O/2Z4Q?^\$08`(!0_`PG*!QO@4=Y_JB,/\U(`J.$OR8DMRPD
M^3$N[WRUX6UX9]7RM4,P^N&=V^"AS0;X'64%G4&J?7HN%ZOU(HGJ(4D!C$_S
M8!_?,M@8-Z`5-_@O!M43;HJCE#H+2["S4>E@A]P3%18U@7R4?2)'$Z!Q.\,C
M[M`P,G*9VC/O7QF*GC?...*L+O7F[,J%C4\;\S[T`!*"`A^%NL)!*A#P49L6
M=,^]Q'3E;>0VB;<1WKZNSP.CN.]7/^AV]4I#2<<9>.!1K94GA;X86*Z.VHO[
MX`;Y_A!U6-VF"#V1.:^`%=S:._^S6G9KY2(2VL/U;\W42LQ6R"7^'FS'S1F1
MF+:Q*5\4[\UY]BWW4/1!16:51HR'Y*\A!/L/2!S83_#U8R&LA0L%FNT##<2/
M,EG97=7#"VQ4668=D[PY/-X)NR<?(0"1C8:D;4A=DYI!BAAPX-.WN/<BH=[?
MMDN+`E9"/TYW?G'JJ=\H52H1.6\S=%W2'XYKX3$/67!=O^5'-FW:=$M&YSI&
M(4_[?>4RC-RF-"DLTT&#(>/<['S!D&\7,W]XQW+^E+6B&#0YR8SA+-W`2O"4
M[;11WW8'BLG&MZ!'NO34;7-(A\3,;-L#'A5M/Y:GD!V@FK(2YJ^NU=6*6)6"
MA=2P&N*/8.8FB+JR'P/A=DMQ4Q\%(XY@O414AW/1ZW'9O-!*)=BC@JUPEM(R
M\[*(:R[![62)I=+_Q(N*ELP$/PNJ>2)0@:T7EBOVK_G?WB)LL<0I1(.(_(=,
MK&)]F6(6IA-I*"6R_I()BZRI2L:GTM)61.2F>.=L_'?]Q[W[%U&Y;-P%-R%\
MET\\<U2.,T="3`UST;&FGXQV:[$S1J"W=+47DH@VDM4GDOQCT[+N1D&+MZR)
MA!W30XR6HI6VR5=1;3-/_>4A*!S1`PMKGX$TUD:B"B$,8N>\ZO+O0G-"L<J1
MPLF.4+<)+1#RQ[2_&?0U0QXLW+FGCG:UZ2!RR5=]%$5C+NWI#T"_]\'Z(/E.
M4K$$2->[J-EK<^PRP+5X8O"<C*J$L5]W)F+R\G#3P$AJN'+R_A`Y-I5:3,\\
MG%DPW0'^Q9\]_F[FAPR$"M3FS78W=JHV&5+[:7U\#!#]>K)65/L>,%F/#QME
MDA=WEYRT-8!2V/NUKC^.+/R+'OIPLK\H.+.49T=<&*N:T#5[OB7R"X%9*)'S
M<#AW#B\=J[RG+YZ[P_@4(Z.(WZ.<S#AU.<U>M-"4O.NC&#9.'.H+/DO%*D47
M8/.)'?J>5A3J<QZ`.R*:!1Y]3+ZC,PY6MJ#?2@$4'U_H8%I3_Q"/D>ZWM,VQ
MUMLMJ;6W0:EEP_5*OHTYYY\X$\_K@GBQ@_<-/J9AA4VO!"<:.4=(89YKX50&
M@[[="?B@X=*OP0QHUXDBD\Z4)JIFB6BW[8VOQ(GITNA`.07+*.A:#B[TLG$3
M$!TFR.['K+5J0K-US#2YYH!]J04D^T\?;1VI0(D38%YHVB+?VJUK61DI6U?J
ME4U2JF@_X*Q.OYV70*ARB.W0WK`?H4F8ZI;O$NMC3U>$N?XJ-B)6+#_ZE41,
MN!&)3E#$2H(V/CU+6:+!U*]O?ULP_5UKF/3]QD_M]0@AGKGU)5*)[@82PY%G
MG"L*"`B%;/S??>+S?'T<[2+O%/OX8:S,@`_S_F"?'W)EO7@91C&6TLO1F5=7
M,+1SHCV!,6%_4E&JX;D]2*P%8<O=PX/V!6K7%O*P=<-EUO#3AA_5AUWNG8-0
M+YW%[A'4`M-_RP4:^Q`%>O'H3HIE'03D;#DT"<@*/4HT#QY'["SZ+'8SF-J/
M._5-ZH[>;M&&(BBJ7YMGM>"SJ7N=N1Y\D<9IU-O&U%9,C.#AXF4KEK<J2EQ`
MOS9P0Y<TA4LPVR,Y*X6KU(!$WWL;LVD^XB%-[YR,=#+J11GG)5(C.$W,XPH0
M!V$K*,M6X>S@FVR/"*\>.\)$D@9&U:5C/C$(P!K3LPIJ19`M8@BGOZ4WC/T,
M)&VD9BU;K"YE-XN*L<2_-!AM<3^`IGQEM</0.OA3?ANW\NP)>56'<]ZYD>8-
MV'@SW?%W5!A#(9/_2BC<_.X\.*6((57BI?H%49'2/D-<CBK@R_PP?J8YBV5#
MVV:XT'SYW+4"7:+4&RX^$_%>#5(+EEC^:3@I:Q,.NBU2C3J2[LQH!\M&N("=
M5-!==\N!A7GU:22Q\Y'\IJBF7V"5EIS#R^<P-P;>7S4V/0!4%/]4Z)^4N1DL
M^'LMYF=S]>_.[:]Y/OC2IKO)&#76W^>1'4U9GRT=<__2"AN^YGGD\ZF!ZU>,
M]P5K5"UF/-@$?9+X#)QF^\K%^,>JYL;9=TB67M21A>Z\EJMO^L[7I4-WH5%N
M[^QQOV\;?<VT>/2<HKGY)?=HVR^PT!&45.N*M)U3<*[A?1O9I]:P8U@89,((
M7>76:RANPQ28L5#@$/W/&NR3]P^PQ@4Z5M3%4CT[..DA1I%EGLG\'8?IA4SP
M@9[R2/TW!UXQ5MV)$!4_MX_`OQV3OR9!S2N&ADK_VO!U_ABM$+B>4#CW^""4
M)FK8LT^$X^K3?@*+6'"J^]*(3"C2TB4PLM*Z?3")LXU;<Y!?;VJA<ZFS;V(J
MAT]7K?G]7-_^!#&P^@A=%@KZ@+FP8AT'>?Z@\_FED=0A86)`06`_WH,\E9;J
MS0EA7T=DNV&M@"D*>#''[?W3\$X8#AU)/MN2`9F)C@1,SB]D5R^%Q6,B19:"
MBT2>76<85UZ4&'_@!#N7(F]9AX=/M^UBUME+P_8B%L@&-C[_K$+MT\-O./LS
MP5(E!?9(+3F_95%Z+OB9*-BP_3!/.9FT'$!'\XU\,J0,9[]JH[LC17!.EZ"`
MFFZBAMHG(-1F,`7ND'"M%VGSJ"0K3_T:F`R*7(P.N*\J&D+86F>%9B9T^J;F
M17HF3=B_%+73KN;RZN6;4('CB1=>T_YS9)/SF)6P6;?IEI9D[.<G#-V*EVVL
MM5&\_U$)-^O?#.TPI4FG2'4:V$Q"2>*T%6!$A;>L#>??"+'=W.OB7XEB1?2S
M'U0@T<3XA^T%DID>H28!U7C'8\-AM[:=K#,K[NX$0/^Q5&W8T&((_3.91A:W
M5N(&Y:;^I[5MZJK1C\Z6(V'_G9&:W54%7T4>Z+\_2-[>^/W3B$E'K7?RF#`#
MU8\$ZG3Q2+937HV2"X%+3>I1D<':3-\O!\/6V>(61VQ,>ED%5RF*T1_DZ5B/
M+VB^)/7P#='O/YAII"O0Z\@U`OB439I:00^QLVK+.#FF4H>-F!'Z'#4B!EYK
M@P7,/3'X?Z"2AXM(3ZCDFJ@G]HX.)MB:9W$KQG*6?:PI5!K*HIW%%F4Q\H,Z
M/E;-E^$2K$"T6`O01_,>,XCC!!N6V4L'TUW1Z*N`&$1T8Q<_.(XGLIQ]96Y7
METPFL'WA?"DO(D+B;4(!6I&)ZIVA52+/0JSZL.$;\YGS7WP5ZXK+]JC2H9ZT
M,KC\"V@I!YZ`%-_U=4T#JFK\O#38J.IE0M^;!:0:='4-AC^K;3IC)=S(Y39X
M0ARI+&]_OGS-:CBMYWTDZ0\N.V.+-0[8RFZ?]8N10O)A66WW4OC'#=:D(H0M
MI,K*6'U)P8O>CFQVX^JS(YTGGB"43^7@-P99JD(-#-]8X<8;/C@W2X]O:J<U
MF6$VV0W/?!]CVMX@B'X^>-%_*"E)]/M7KMQ91Q1OQ[Z`(+#VU$&60C!,T3&E
MZFW^8V$<N\2`+U50X$L`Z5=)`"_K=(^W)&Z0UCNJV&$+.H7O`6P<]/0=F+KG
M,U\D7LOGZ,#4<N*VE48#NP[I.<^(*3;B)!K*86;2VPC"=<0<ES7E>'9Q%,W/
MNO^CV<6(F^V6,E)MZZ('7I>^08SVT,$]!5EEA/:*.I703D0K5F7HA;*V2;[&
M*42&4+AZ*-.#5#Y-E,Z]-S,"9=`7(5"1_.=:DYIQZ%QCSX,C&GH;&C9S$5/5
M`P$N'G_(TAWE,L'TV0V/Q[FKQ^7?)]02A13*=%&KH)V"Z>OEDG=7%)Q"I:D-
M+;12BK<H-ST\'TV*^Q,!3LN:S5VRJ<.UBUDV\W[S?W;/)9X^O.5/K$U`:SL5
M.S6@H+NN$6W33:\T[$U_<7>5G%>X!J/N!3GR%%)3I@3?\,>%+DY,K,T1UUFN
MN8R:ZDDN@^)%A^E&WTVML084_W.AY$]FQN,"?T8[]A:ZPN@<'FPN"E-`0KJ@
MJ)MSY.,+RAY==G-NEI:F$B9"RHT:BAX@>S*9X@\9T7R70SK.(U]3FE_KUU-U
MG<!=U.6O8EPZ83\2*";A\@D!"(\*/=+$SVJ4$E(<$W/RXSLOS12'OW:?MY=3
M#($F?!//%8T;^6DRM6>SIY0M\P-G.%IH?C2^`>1-4,V==:>7GZ[8`&W"'F3;
M)SUW"A2ZF3;/AK+SC^5+K@)'9H1[ME=&&Y3C\99K\I'W/3AW/KUE6XQI+<N,
M3+AX/9QFD^[@YTQD]O?,CY[9S9;)U(#6>)!,FN#.7<:XCH$P<D,0]./O8X)!
MMCJ]34^HXH*GW?R72*@J,)U$T*^'.JR'[99[Y44,8J/!+<9=BG]$@>O_#.;=
MV*Q"[</57O%'[+\VIDX2'7)\K&32VA-P">6XHTAWC2I>URUX!K%536ZJ0_SN
M=[;](:`/09/YW9GU!\65O7N*``A&,4,<&$DNR/'30D#I8P,2LF/R3@'9O(+`
MA^'U/.2\LXRX2MMFWCN,L;NW\/[>C4E*W%P5*AF;#S3&^087E+&7&J#>WXB6
M80]]QSD@/,PJUP"Z;R8:YEJ7:-W`[O/4;K<F\N4UQ,3H>MI+N[+/M%'2?0%'
M">FT^>3"GJ!9P/V&D)^$TV",1HG!^HMJX(*R_U1[8_A5-'AN(__$]'.2G#;D
M"QV(EI4_.'>&=>B5X=7BX3R"E\,S"KJ"+%;Q%R2;!W$X./KWN_S,'!9480W\
ME-J6.&E('3SZI,WUU^\V"S&5,(@MS:!<(8!FXJN/-IJ/+62IRY[9F)TRU7*<
MQ["R-!==7M+E)'&)J)H/PV4_R($&;=,7LVFEGS/-+`_,)MD=A_,JZB"4;RZ:
M=10$&^JF4?G$)'>H])?>14+Y*?01)+UZQ-/`!XE"_"!D,9K#N]>HH4%&42+@
MC@X!<'OR>M.WKO7KW!9#VJJO1Q!`Q-S8@$"?)?MF%_L44&_3D&_L[WUH+AMZ
M;5IBL'K,Y9'-VA1_M'0G&W4E!NB'F^^_7+)V6]^<"X;'$C1[9Z(UMZGO<+EE
MJ[TN(DF(VG)];^"?/A'7O^LA9^Q>:<^56R;`(5"O%6<Y0A<U!H'T21*?);?F
M0OC[K%TKS2'4Z&-C4/;-9-^PZXWL:;QMEQ=MTE48@=Q4QT3!I+D](^5HJ_&O
M12LUHI$8A24FKYL"&+&JTZJ>+"II<1#[&1[7/-V*/FGVKY>?`W`\#J!8%W1F
M`BU`.?(';;/+K+M!/A.&J![TZ4V);%Q>SM)%_9%Y*P]6%S3K&,;F9I65/91+
M>B7)T5-$87X67@4.>PU>ML%R%NX"]!Y=,+6?:RN(F4EL^N_XD0`6>J`WI0='
M5%SW6:D#*(Q4!K#Z)>LSQYT6)H>WNN/DD%;>55%X/.\CP[[?[>=!RE2UA7'Q
M;9!%Q;.([M<?GVTW)RU0(")U^W6Q'*]>Y@R&(8,D\UI/FFSZ\/2DVW03A!]E
M=%N[P.>CG=U3D"^HHA7C#)X!)_OT72<EMUD5.^3NS!6H#>K&ST<SDL-$K&4=
M9U_O1)<LUB59&AFHY%(].F4(5_;&=U:VRE1S7^M_60[5)9J0E5A[4<;TH]"V
M/5I2-@E2F%\]S:VJ1Q]7%!&M.T<A17JBIJ?.(IH<?8>7O#&#TGF]?_I$L=?J
M?R^SEJZ)C2J:ODWR-6'<>\*SC.2I\"__=F,2JVAF9)(4]$-7G;JW69QF1F&$
MRMUKA9OS_OYL/''P!Y,`M+Y01NO$R*;QQ_?(Q9W#Z-VL[\L6(.F:@!#)P)'#
M=;_<.D+NAJ:@MGB15%[?@**9`=UCL#NM8Z+K>S\BXYC^7?B9*6>1_=&=NP%?
MK^*DMV7S])^@$B7F7"=][%R?O\LC2?`&`R\'AW[:GJYMX"#^`.]"0/ICU,BM
M*>I3"/03V`#I]U?0Z@?2M!`TVD/=C'?I4D"?:"5U5O)AKH"8TSA8Q[K]+@,5
M7H6-(;M2",JJ=_YJ/DS9=W+`37Y4;X)`BK#$*=&+8G&S@&[_5X!",X4'C#*&
M:@.1,5GC7%<.GU$6'25'!JED\ADSE?]SU]F,#>\JSH@'R(:Z#+?>PR-'P:/8
M>ICGY*Y<]]$/8Y5#\8.64YP@0?;E9>@0[/`47`41SY``HX$CDT9!`6"$R&**
MC\3>6Y./:XI<"%7P0?#;<,PO,46@Q[WXB?3L&STZXS?<Q38171+#V3D>:39\
M`@QKP>NY.M#BZHN?]P(!!9GI<OI=U0-?23.&)F/'?O2+Y:6/QM/SATSF'#J#
M*J=\2V6[$X(=#K+JYRU26I"1>[!S"#;O?MNTU5@G*]Q*JEEH6'BFN=HMX_K.
MG34/TTW?-_%!XMQ%99G88SZ*+T-WUQC?WEV@IH95N=<M6$;RNQP<T*6IV3P^
M:0O#S5U&<S.G5U,Z,;I5JD39<LZLX-)SK\U&;*EFH5]I6@U4B/,]NK%!SJUU
MN/TKVGS`P0;@]O[:H&4D5_]?EUN6(;*FL2&BAVS<9X503_0'L:T[07CQL1$:
MMP[Y$0:T!?%J3V:'5&&W\@>UX2/24F3`[GI'#>O<QBWG^&*)-@09.JV9"J=_
MHC:POA/;_%(=R*Y'0:XZ7_1^?);K=(C?2;5RK%&OK,C:H6CN._4J+8\9@5!F
M\J2_P*K",UY9HR'134!/49O9G0+^5_OEPEJY<>HW+H]7@#GSF"8PQ&FEV&YI
M@H9MAP98FJ7M=5$KTB)+MR*B?7Q6D_Q`)B_C&^\#WWD<2^&1;FU)P>B7Q;^Z
M"E0Y8OFA$[)48>3OY_F[RVFDO<[5,FM#C'A+C?*Y'?[3?9#<<R$"3%K3_HHD
M&TB-7\?!?\8B"?@R^#I1YI)P9M<=:8-PC9M#8GC,W")G4"V7H5_S[3KJ:?-&
MP^!!AOVLB<%RI0&FOD\.+XLJYGNB^>KA33=!L^4$G%4:M&`U;XGUS$"JP2(T
M&DO3]4ZU$S+_][U,W.N=[0A(`:8$J2]^Q%T>+:FNBN@^$"`7+*8W$1T:R5%P
M-A2>=-+1SSRCCYE5Z1<T[CY-J]<Q,8(*A<@^CK.RM5&O`K\E%X2AP@EN;17A
M5FB2&+(:E]V2(/5&E'FO]7M_=\,PL?-VUK/)AY.AJW1$!B0WX#+@B"-\FPWT
MU?>FT@1I?HN*OD]#?;X7<CU]W^LZM4*\Q\0$%[QCH?=`I[RN-@Q1Z[G[_+*P
MU_WW_C+;1V5Z,L>;]D_0S'+[ME4OH\B5Q.PJ3H0VD)]'@*W1`<X'T2S=>K='
M9])>61J[T%N_1ACG0A9I9B$^3$3[A37"1_Y+2^B>"1_;U+V-CJB,/BWY+('\
M6R'_`*2=T-D=\F8N<#,R=4,1NZM0UM7R(\!!^K>>A?*'3\T;G;^XV/AAMW8K
M>,!P&5*-3NQ7T>Y<X+VEA^ZM'2.PA<3Y%>V?L!KYZ1TT]D2@;(\67:)P5L)A
M%5Z$.[M0M%,!/H@0\L*7LU<TAS+9?_DW52"@9.;#3-I,6HTT"'J89R`1MD,A
L"0*(,_EZDOG9:/(T$;3&_FX%NOB/`*V`*>)$=3B@U*"@D/\+-TQ!@1XC```A
`
end
SHAR_EOF
${echo} gunzipping file bio-linux-keyring.deb &&

gzip -dc ${lock_dir}/gzi > 'bio-linux-keyring.deb' && \
  chmod 0664 'bio-linux-keyring.deb'
if test $? -ne 0
then ${echo} "restore of bio-linux-keyring.deb failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'bio-linux-keyring.deb': 'MD5 check failed'
       ) << \SHAR_EOF
3875b96493f1e0453d107c1adcdf90c7  bio-linux-keyring.deb
SHAR_EOF

else
test `LC_ALL=C wc -c < 'bio-linux-keyring.deb'` -ne 8990 && \
  ${echo} "restoration warning:  size of 'bio-linux-keyring.deb' is not 8990"
  fi
# ============= pick_cran_mirror.py ==============
${echo} "x - extracting pick_cran_mirror.py gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh09863/gzi
M'XL(""*8C%,"`W!I8VM?8W)A;E]M:7)R;W(N<'D`A5AM;]LX$OX<_0K605$)
MD.4XZ0)ML.FAZ76+8-NT2-,M%ME`H"7:YH46M21MQ_?K[QE2DB5?V@U:0Q*'
M,\^\#WG\;+*V9C*3U414&U;OW%)7T7$MBX>\,+S*5](8;;)ZQ\:L,(([4;+O
M^/^)[]CI*S9]?3Y]=7XZ99=?;]GIR?1E%!VS2U'PM17LADG+K&:\KKE2LEJH
M'2MX\9`R7I7LR^[#[>]$P;?"ZI5(V5(8\0+O6"(8C%`(PYSV3VRGUX:]NWE[
MS1I0).N=+@6;<0M(V+%TKK;GDTDI-D+I6IAL48%UILUBXI_&?@6_*VTGUO&9
M$A-GA-A(L<VM7-5*Y$I:9YTV`EIG2[=2F8!)/.:M=$O`5#6;&[UB;BEMRO2<
M%8!FQ3FH"`$`!$..%^YA?#9V:W"37&6P7^F6HM2%]9!$-5&PJ'63P+_'`-B*
M![T19J[T-BOT:O+W&H125W;R^O7+7\Y>3?M"EGH[=GILA1MS_"I1P%%C@Z\-
M0:MD%'GD"PDPM;82R'8,>FOCV`<'UWPH'WY"\H57"QTU+PL9>:*_U]*('%@M
MX,4CL!FE;'26G8R2J*6U.UC*&5Z(F8\`;=N5PFZBJ-!JO:HLNV!WHT_>NZ,T
M8ON_T;>;CZ-[<OB?PK*K%RL&6RB%</*!Y3W!-AQ6AD=9#;.(F=8/6=0]$FLP
MB`K%K66?=M]E5>IM#+#9V[I6LN!DW/`U.8^\\%+,69[+2KH\CV'5>4JQC-46
M%NT.6[(#.B>=$A>C+Q2X?W:!VZI&;%J1%\2RXTB[,[@QAVR^5@Y!^5\1G_YR
MDK*7)R=/T,VT*87)MQ*1%4]!$1WYM=4NK[034'MTK1V#G2A0$7U(3&X$,T)Y
M8V6,7<V9K%BIUS-'9@5B'^???F?QI4$R:)5D(_`]_DWQ!7'26\L*)7@5?M=U
M(W/.I4(B7K#?N+*B1=)H@L_C:?-):5[FG6OB#G2(7!B%8(^B3MMC`LY*[C@A
MI><5\EZQV&TU(!N$@&5S;9C@Q9(A[!%@E>B^]/B$0-O;L4MV2"1O?L3[5WJ/
MP38EWDEO-UPE4`8(P(8K).0`3D=(<B4M=2J>]X-Y+S0+#&.9]'7EK,U6JGU6
MB+WV?E?YM%2_(6AQB_U_X#7V%!>=O+XNG;F"28;@4_I:\94@4:):KX1!H8J;
M-$V&ZL"J0BD#15#`?;T.SQZC$X]N0$VT#<QW>+QIMMV"+DX.^+8,6H7GTEC7
M`&9VJ=>J9#./<:95.4=U&3"0"&QV<<%.AGA;%%EM=&VSK9"+)1)-4(C>FK7X
M9V(0^DJ8??>OV>7GC_]^`GH#%*6I:9T'--12I/,]T,<!/`OC>:7;<MW?0!^:
MB,D#Z[CO['?A4^.XU*-.O?DN9))$1QV+!<I&X\DXN9/WOHY8U.+F:RX/(Y(@
M*3Y#QFT%H]9.<8F>XQ>ZI!T6IT#?9!4]Q\D3!%XV88Q'?U6LTGMN:!Y'!W2^
MR.7%DAL;G_E2=\S(;4V%02F[I3Z@D'`6)D0EVV49%;@V5I9\`[RU=C3&^*02
M5H:$*L4CL2O7)O03*(PBQ69KQ!L*W17[SQJAYRAX]YE)4.'!?S'V=IFRG4"/
M0[JN:.K)V/D8&B`$!T7PC8_&O2](K0+#@S9QGZ[O+EL8K53N=$X>'9"EY(R<
M*[FH+BAR4ZI]S?M)=MIP\3MR79'EJH4HXWU=NNMSNV<#IV^7HD(M`D<_QS5#
M14H1*U;2T:!F(8@/*Y"/KLZ)<8+9I:KP$H\:Z:,T`-KC"8Y$R]"^"2DQ+M`<
M'\@/C=\"O]:_LMIHM4'QA5\PSE4.V4_.(_%BUH3<>UJXU(^]J//P.CCPK,-P
M5!MA[=BSZ2,C`!TR%ERPH\;)R?-+5)LN3SU?Q&I#$\1_]6^B;,:,I%M_NFD/
M5FL-Z3N?VU_\X^VN%MGU^S_>WZ3LX.O;;[>?/[V]O7H''L<M$UZ6.;7PG)#1
MD!730P*?^I'`)RV:/2:E4L[GJ+Y5@2%:N*T051BE4)F0.7M8X!AX#)&N)$RE
M*P?CY4M?"F,_I0R(EN*Q!K^8`O1@:3-8"K8.?O'YA3.&#T),_GYF6:+X[<)P
M,BP\1_JAV1:L?^E?R.KM@A?G*TD\\D&$!'@VZA/LXS3XOA<-^H'`J9F:'M0S
M_RU8@IN'=4U%[-?9F^?VU\GLS5_5B#T//"@G_$08)P>=?F&D+_K<.>K%I!:B
M`O2V(_,D0>X'//8"FE:RL#,F)"G[T1_&1_P[3=GTZ=U[I?K#8Y)VNZ<_V]VX
M-/VA[-.?[NZ*?/KT[C,O_@>[6_\]+7S:V]VW^][:K0."Y2E9AUV*(I]HDOV1
MH%=)P[#?!6)O,#IF<&)O5.7-W"@=C5*:AB/N6*UE1974/3W@=MS"()?ZW0F"
MH9/8*[>"0H,:#A&Q9Q?L&C%^_H,6X/G=$>5]3[/\_U0S_C2T5\HV2H7N3H'+
M*G1#/PV#!<TF5+=U]8^CP;#S/[>4+#'$W9W<)\D3YP%:FMYWC(QP:U.%>6W@
MF9"]#?R02VEH$U`$YHG]<^90/6DVQ'DW]`I?3O/3RV^WMY^O\R\W[[]^3?K6
M\W4@)IL.0P$?@ZP0A[2GQ@SAXJ$&27<:PIE"[^(>DX/3$)$1EV/V$0LVF!L3
M/)W?PLV';:\?8&&'P.*FQ&BL:&0)9TK?*<7^0"PML:/#,F:=_9&XT#A+L\H;
MS'/K+Y4"]=^976.#%<UR.*O[2PQA8@U7QR-_>V0QD(G)S:34Q82.N<VED<U`
M/FHG3W^L*!_3,$_T#Q6D6[Q2R=WT_)[T/MH?WYOCT5T("[_W[NR>(O:(/!D^
MDQ='_</JR'/I'+<_?T)^="0>"U&[OF>[8VLW_.^O"7IW`X=W!3^\)2#Q![3#
MZX&>[TN=<\3'A@S1[MT;'04)L+K+BK#WJ#G:H$(300.?5*8W&LLQ`?KN-%#U
MF%T+T1PQ^$9+FH9#I@KR5B#J;F@R'\,Y.,3M%+FSF7B4+IX29V5%Q_<[-Q4E
M_9A0[1&%J3&4"SB2T68;NC?F?"^4K3!\\86@`@C,6<L1_=O7QQ>@IS)YQ;8<
M8Q[%T&K'ZK6IM14VZTPQ-$,?:=_0R!7CT*0;._<O<?JN.J2,(D)_<1`,240B
@B-*MZ=X*-)E95S$)YV:Q2:(.1H\PB?X'G^7Z/W(5``"N
`
end
SHAR_EOF
${echo} gunzipping file pick_cran_mirror.py &&

gzip -dc ${lock_dir}/gzi > 'pick_cran_mirror.py' && \
  chmod 0764 'pick_cran_mirror.py'
if test $? -ne 0
then ${echo} "restore of pick_cran_mirror.py failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'pick_cran_mirror.py': 'MD5 check failed'
       ) << \SHAR_EOF
1eea77154b2c1f774fe8fdf88b5a8a87  pick_cran_mirror.py
SHAR_EOF

else
test `LC_ALL=C wc -c < 'pick_cran_mirror.py'` -ne 5490 && \
  ${echo} "restoration warning:  size of 'pick_cran_mirror.py' is not 5490"
  fi
# ============= sources.list.clean ==============
${echo} "x - extracting sources.list.clean gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh09863/gzi
M'XL("*'PA5,"`W-O=7)C97,N;&ES="YC;&5A;@"U5DUO&C$0O?,K1N*05@I+
M/E`/N?4CATB41`FHJJHJ\MJSK-O%7OD#NO^^,[ML(*$D!-(#$AC[S;R9-\_N
M*DQ!*F=G%S\F:30APND@.1G`<'P']V,7?:A@+')W#SWX6)2Y`#%3'P;P[NSD
M='!R?G;^_F<?0K-O)K0!ASXX+0.J3J<+=XB0AU!>]/LY%F42ZQB)M+,^?6;1
MZ%#U)^74"84C&]!#9AWD=@'!0FS6Z2LA&5R@@SDZKZWQ8#,(.8+2'"V-@1:3
M#I-91INFB7`RUW-<C]E\[4/I4&J/&QD30,\[>1A(I]N%K^(7\4CC%#+]AX@H
MP=Q*9U64J$!D@<@P@4P;4=#I`@5!-:P8X#!BO3;B6Q#<"L9YCI)/"7B;A85P
MQ(:$1`RTIVVE]3I85P']NAR-KVXOA]]A,KJ;W-Q<WXXOOT!:U15H9,=8`<4L
M(95Y>PQE4Q!#FJ!=(JQB4`XD&Q8"PK>KX1!&UV,*)Y'60)B*D1S.-2Z`6M#F
MOLRL#0<>970DOB;HZY73IK"?9-9/[]>+@^)OHKQE*Z'MY3&U0Y%J*FXCI$Q;
MD>P%89,M%%JBD9C`3=-J+X+V6065C911D8'P;`(,QDO@]#0/]5+T6(=K<]U)
M,XPSBT5X1CDORX9!#E7.*HD][>;1^3TG^;`<_H6SHX):->2":IXB&BJC#VR)
MGA'P3T#C";*HZOYS%Z4U@9R']E`;N1=+'ZJ[31HK0F[C-`<=:(,LHL(::O/"
M\'9&?2Y+4IX(]>(BUS*O<R)KGFNZ:TA;62P@0Q$B65W"2#NH*Q7R=VD=Z?,9
M83'6_[.DWBJ')T:]\LM#^_ZZ$.L46G*;Z`_@#_Q?N+0.A-H'9IO;[HNQ%Y6M
MO=L3A>4X,?P,0Q.:QX@M"KO09@IA8<F@#=9^*Y1Z,M6?A;&&IJ@XJD?MJ!0N
M&'1':Y->3\Z8IW\U)[X>?=[,X]C(_IA>28'_LEF&CI1$=\D#?'V!+%]$U,42
M)2=/0VV4=9X=0M#8N#E=)9SH<I!HAAU/+JQ5NA6W;*'7J[1\ORY9-`?7"_R:
MPP?0)J]TJL?[ZD>,0K)!6Q(7\BD+"\%=LN!S77)-M(."?61E1(\\@YS4";]=
2$O5H/%72;H?^`JT<:(`U#```
`
end
SHAR_EOF
${echo} gunzipping file sources.list.clean &&

gzip -dc ${lock_dir}/gzi > 'sources.list.clean' && \
  chmod 0644 'sources.list.clean'
if test $? -ne 0
then ${echo} "restore of sources.list.clean failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'sources.list.clean': 'MD5 check failed'
       ) << \SHAR_EOF
6ea187fb13c9c014f204ef6c411c10a9  sources.list.clean
SHAR_EOF

else
test `LC_ALL=C wc -c < 'sources.list.clean'` -ne 3125 && \
  ${echo} "restoration warning:  size of 'sources.list.clean' is not 3125"
  fi
# ============= bl_install_master_list.sh ==============
${echo} "x - extracting bl_install_master_list.sh gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh09863/gzi
M'XL("/G;ME,"`V)L7VEN<W1A;&Q?;6%S=&5R7VQI<W0N<V@`E57?;]LV$'Z.
M_HJS+$1I,5IQ%@1#.K<HL'5/Z\-:;`]Q9]$F;7.62$6DZAA)_O?>4;^LI-DP
M/P0(=??=Q^_N/HY'R5+I9,GM-K#2`:N"8`SOP:Y*53AP!K8R*^!@*E#:.IYE
MP&%9Z=46S!H*OMKQC;0_P&VE5KOL`':GBD+I#8*XK;$2>%9*+@YMMA23(%/6
MK54F9Y-DF2UR;ITL%PW4@CY.W)T+`K6&$=P`DQ!&;4H(7^`-(DL=`/[D:FL@
M_%U9BR5;-D#!<)3R!N2=<C`-ULJCWB#@_?2:/88P@U!4>?$$=L7=H.8#6"D@
MMLG\=93`#6/:L.8^K)0KD^=2"_LEB6M25.R\+Y8J@;*F6.O\>^S_J+0F]MQ"
M:0QV`/8*56[57IL24,%L$OH<.IZ%O'!L@]UJ@]@!PD!F5A[A?D2L\OO8_U0H
M4%$J[8#(<R0_@/<`MA(&GA0*_:W&GTSIP%0.\BISBO%RM9T$2^7LU>7LO%$X
M%<5N`XSY,CY$.;ER52E3DIWGXNIR*$<#,*V)/%?N]!0VI2R`W4)\K7[\Z2J*
M!UW"[W.?B[\1#,JCB%)M]("&Q;8V>'=`<"V7DS'\JODR(^'Z"T)NA`Q.&E@N
MQ`#,`P0GK5Q5(;BKFX&"D69K7!FGC,;_M<CK@44H>_8JN/=Q8_B+6E-W!7F`
MYCER/%HRT,;U:]0D_6+P@]LJ"\L#T"@3:TKW2X#9.VWV^FA1.[G'_O;#>%Z7
MQFFF5`]+VDY\0N'R@J)F:;YS,B_2H.]45#</.S4=-A5\(]AM)<L#L*S5//Y;
MJ1C_X?L=Q/?UI:.+\#J,+A_I?!Z<0+MTUY/7\S/Z\RJ93Q,$QZ/YF1^@^0-J
M@>=)#&]Q%EJ&]2QW^_"_./CR?>5GT-!V]3^-(HF[";O[^@'8^AE#^KC`29Q%
M[VHMRWQ0ZNWIA3\FPVIC0QBU1E)*'#T-F/Q(IOW)\;+$\MV\T"2^X%7(TP6V
M3EC0',["E*@SW;$O8OCY^')IB%.,9N1,ZSI*0_IDG%.D)4PW&+431<>%PDZ4
M#[AW8=3!A=W^173R(O,^`QX>6F?O^MTDOQA$NRB,EB389P,"G14]T6V!ZP/.
MNU\&;.H>';-;-7SOG%^^JF#.,+_:_^[LK0^@+PO4CU7%IN1H']X]/YH]9,;L
MZ'&U4L*>"G9-$TKHN-MSBG82*GQ(<2&];MZ\'5$G[R&5L2PZ$%'&2Y`O%Y4+
M2/J@UO]/6:KUH;N;_(I[4-^U?Y0G$_+V02_[:<9';\T5*8%UFYQ^NN.X>>BB
J=\_W?_P;A5B^1P%;:OT;]1[[LS%&C(Y?+VK6A9>J>4F_`6E3\5&D"```
`
end
SHAR_EOF
${echo} gunzipping file bl_install_master_list.sh &&

gzip -dc ${lock_dir}/gzi > 'bl_install_master_list.sh' && \
  chmod 0775 'bl_install_master_list.sh'
if test $? -ne 0
then ${echo} "restore of bl_install_master_list.sh failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'bl_install_master_list.sh': 'MD5 check failed'
       ) << \SHAR_EOF
2f699a25f95001a61cbffe4d02a85573  bl_install_master_list.sh
SHAR_EOF

else
test `LC_ALL=C wc -c < 'bl_install_master_list.sh'` -ne 2212 && \
  ${echo} "restoration warning:  size of 'bl_install_master_list.sh' is not 2212"
  fi
# ============= upgrade_to_8.sh ==============
${echo} "x - extracting upgrade_to_8.sh gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh09863/gzi
M'XL("%8YA%4"`W5P9W)A9&5?=&]?."YS:`#56VUWV[:2_ES]"D1V(ML5R3A-
MFZQ;)]>.G<2[KNWCE_;FQ(U-D9"$BB(9@+2L)MG?OL\,0)&RY#3W[GY9G[:2
M2&`PF-=G!NC*@Z"GTJ`7FF%K19P/E1'XIQA*L:LR[U"EY:UX+LH\#@LI3*15
M7OA"'!0BEKE,8R.R5(2B+R>BKQ)IQ&2HHJ&(PA34>E*H-$K*6,:B-Q5Y&(U4
MX>=2)UTW+DQ,)F1J2BWMHG8%H<O4B-`(G64%:(@0U`HYSC,=ZJF(E991D>FI
MWR*>,S$.1Q)<&)GTO2A+BU"E6/)&:J/`WD050\>N3",ES19FK3;9P?X&.HSE
M59%=/??-4+RHGM`O++*]?<"\T'J_2F/"@11%)DJ#);`5F1+S4V*[L0O?]VGF
M:S&V,S;]XI8I[,D>2\MR-I)3K=(!Y)[.9O0@^X1D[[FW?BQ[-/4(@C99J2-I
M_$29P@YO/O&C1$+Z&/OJ=.=(C)76F1:YBD922VW'TZ^K2(?IE7WMYU/>66@*
MJ5DPM,&:?B^Y&O.[*_?NBE>B[53O56J*,)F-X_<L.G%B9!EG7J;S80BMTAO1
M9Y;2%#MS'/&@*S?("BI,I]C]VKKXU!+XTS*,A9>+]@F,!=:13DETI`92.80E
M(;ZV\-)-'BZC829^YH_6EU:+?UY/86;;XK,8,JU(/']\+58[EVFG%87%O)[N
MG>#XHJV]*8F3"0:"N22!`81-`Q">2&&_85D,,ZV*L%`W4O3*`C(821JM!L/"
M;YWN[QQ>G.V?;J^N08:8%3V\$-=%,15/7@2QO`G2,DFNFS_66:[X`LV/I<AU
M%LF8?2@KR5\@DWZ91@6LW["L279A3R6JF+8P3!97SF1843,1]_II.);;[3E[
MNF;7__[ANX?CA_&U7X3:'_S5;O$$U1</Q'OA2=$.9!$%85X$JY9*6_P!\4,8
M*8]<$U$LJC%X<<E/A0`Y;/@F[(OV;&)S^7G;CL6ZF\?J:1\G,6F_KP:E#FF[
MPH0W<'V$C@5^>&)?6<;U6'C]>LS\(L&&]2T>N7*0]N$4DR$9B'6F@J(D^;[@
M3W)/-U8<@)TR(09&;`@\"NH@CQ-]G8U%4!H=F&&H96"CJC<.4UB=#BQUXT?]
M`5L)+\,R2+)L!#N32H-R&KNUXDR:M$-FF_+6!ST_U-$01N:7O3(M2C_">MBB
M+_*D-!@/3A$F"RVE"PBT@5"<')SON!T0#WJ[?0VA>%$880=YEJAHBFUI618J
M,7"&@9:Y\#+1^2`N/SV__/+^L?<??UQ^+]Z'WE_XW`J"]Q_>;QG$"KGU!QYT
M,"><C$3G4XY85HC5H]=?Z%F9JH_7[<J08$9_P0B8`S*>SY_QZ-KJN7KZ64PB
MX<$9'FR+S=K`OK.C7H5IROF"%!;+?E@FE<Z0LWY7\)>1!.O5JZPOAD61@]^E
MHO/;%>%W64DI340(3A3Y6?_()EI<MO>R29IDB`ZD742@RS8E+`X"6;^80,^5
M"<-/)3A##L+WGH1?RMD*R!P4#*W-V-1#R\.@;%SE%VR=0AQ*V+A0!=D5/;Y@
MCH6+P-;>7,*FUUHB(1@IR`G\UG<4Z!;S!3+>4F>PH30QTKF=@7.U3?=K8@OL
MUZ"[H#N:W#'!^^YE\.B/X!)_CX)!Y[K;1C3X3ORK7,&5OU`</(!!*U#&K@>R
M$*<S=PN;&;#++@6A00=P2D.C8I)?R`%3ZC"B\)Q,(>!==CXD]0.0I\BNB//*
MM1ELC*<">J<HZSR)4C<;7C.OS@)K5/E5/D4N2)<EX.LZI#I/B.9=H7X`XV^O
M?K*_'CX4&U_:"Z[@%#293'S**<;O:67\,/++47`:M&NUNO$5[3G)[D"@J=0J
MHIVG1>QVS'FE-7NTMMZRFR0'0`Y;`[7-MOA>/!;K-EI3!B)X(ZZ-_"A6.0QZ
MFV+S&DS'F6/!2S'/B#:>F82\U*;Q.$NE2^/B,;.%/[$3%668S&`IDDAAD*,U
M00"V"6.==(P0!BSH!K*-;#[U'S]]2;NKG+!+45J<6,U4H!$C;1RIURA*X[.]
MF2$;`M)N+^PAC]/TQ/2\RM/(T@XZ8T[^!&V%O(5U82`C1=@@[-3`&Y#[3][]
MMG]ZMGT=YZ.!\!`B+!?65R`2N,N'WRQ+6^)RS=^X7`\N-X.\<]WBW&OG`?2.
M<T0:SW%OQ!/_F?^C]U@`9*[:-9K)>!;5=+7M"O-5VX?LJGEK2OJ@8TBD<$FF
MO.[PNTICA8`B3;M!EWUJ2L2)K9(@Y1`)F:0QA8/V)(304(@+7ZP7L7:N2U-,
MU_V:8(/R.<)97VED1.R6X[>-EZPA1D&&$[-IQD4$TQS,UN;B\BW6;G+MHB[/
MI&1'U'D39@I$.T98.)^M!3A`R03U31+"'X;8"-DXAF.7$[])]G66)-E$4`BG
M`*U+B\JZ-L"$?2*F90^U!85_6T!0=FD67"(<H**Y*Y(*AC(8V.<:RH:SADRJ
MK8+B@+,_Q4:X7VXAN-LSS-HBBB.H*)4D12JS8&`'S!'0NS-MKY*2+<&2Z0,X
M1!VU'**Z@VONS#5UL,)<%W_$AN`MV!R(3<P&4P*5*?P,0D8(^:8%-D2;::\Y
MJ'(CVA]6#-G>M%%:(1W?`#I5TRX_?WA_DO_!TMEN?]M"/_,RE:Y/[-RD,';Y
M]2I__0T9/Y63U@I/&=]\JQ1ITC<-K*6\=WRT[_15X>"5BY1<'[ERK%(U#I,`
M@2Z-0QUSSEN$`I6V7E%^)FV5N=@Y.;^#PDD!MF:[6VO850E>4K+VILY2:^+,
MY/Q:IW*<W=!:7.T4.BMA#;;RL6'+S!9L$-8T2[J(ZEE0@F3"#0*=)5X>IC*Q
M['#;X\]P;!J^TQ4V9CFSNPEUD&2#`'*964PP)K?$T_N6SDP!`S0?L5A"?0;O
MN?_TSE/+'9ZW&JQ4T07&FP!$<_=$>[#<R/MX$R:H=(78H=:)6V@0)N'MU$.M
M@?CM(=986I2')F##`I\>Z3FAZ&7=W:8.5%\>0D$D:=H]A!H[\[R\U`-9+:P]
M`C&.J;\96ZB!]@:)&H^EMIOM+`:6#E7X\(`]B/G"/OI-R<F;8O1#56+M903%
M*"R$/2IW(UW6*@([9OA2B+<2NTDSEE-"NZ=BB<(@?&16F'7KC$CM)8NRQ[:5
M`[C?(;"89]I&5,FEGPW8$(P_*R-UO[%TL-&TW8V-C?:=]#5+,]E<@TW5^9&2
M9B(1O#V4;8PG;'YP*6.6(N[)#0NK'M`N9$CMJ/N8`;6CXW/Q;O]<O#K^]>1P
M_WR_7OUT?_?X^-RM?GIQ),[?'IR)LU>G!W#[G3<[!T?WK'X+L6^V*-*LB./_
MZL)[*3O:/&UK]`DE$IL[=P^?D;+BF(4->:H,)2O)G]MU3\!/+:^3DQT\^P'/
MHB?QTQ+??YQ[_X]4]B*Q1OJ"Z?=4+U'9RY=5^<Y81E$S$:&N8)XFTF+`DYTN
M%=@PL`F]XBJ.X/.#=:RQB36XHOB'V`6:%FLT<TS1DGJ1/.0G#'F390/`KE=#
M31&*J)V'R4B<).4`5KK&6Q)9FDQIPE-,N'TRR&AIL0:19#E>6V#T&G7ZT3_I
M#8U\AI&DLU]WH)P]:49%EG?%,,M1SU#K*12QSG(/2[BH06T!%NV;E!BA;[P2
M-RT9)3O0@,T/J:(,N3Z>&NCA-?7G9)93CQ)*A9+(&QAGVZ;E[J%UDX2""HG)
M]2F[(`L]_PD01Z(IN2OF*E-R0\;H+1MZ]M\HX0?WMCK/LW2*8$G%6<Q]+?"9
MDN&0];<:<:8B7]7;2.R0BBZ4-`2,QRA6&"N[EG,<>S29]:!(<Z)NK"V"Y%<<
M!QHVNV0^+4)Z=DX<WH0J(<"RQ`^`L!HH;?<0GC\FW#UL=JSN=*-ZR7._*NYC
MGQI<5L@@ZRJ1'L'BE(/*W?#`[7E:IY?=0NF,TQY0P^[;5YMOY(U'P'X4I>\A
MT%IY@3\.T20Y14UWJ_<XBTS+^9%1:<15=%A07[\P=<'E`#CAR\IC)YB-G?5Z
MR@R[MKA7KD/;/M=3!VQIZS78/ZTF8Q0\BCI`!WTKFGY(?:R)[$#A52_(]5+(
ML8LL@=BH_S(KVQ<J>U3KU$AY<9\4.2U2L@5:T+:1^<LOJ!X/^9$XY;PY@R\M
MF+QP)3@?Q[!#N$8*``^51`$-\HR._GX@._<3#CT_\'^?.EDAO)*L*-8TS+=B
M_:Z`%+GP=%;CP8XF8!.N<#N]`_>4,27)B_H`!+.]C-(E&7[+(@)RFL:*<-H\
M#[<H2M?^_]6AXU"7L!1D60[X7QM*08Y0+!S0MC%^_+JJZ@"4R$$832MMM7U"
M\752L6]KR+DVBV^]4B4V/6MI@X!PNJ+`[;I)]A64'B;81VH/`YR)3EU_$:&9
M.@QD#:Z!0W!39[[+87ZF!S6_0<5*(,K4;KBN;EH-(B1GE`LZ<@V@FL*RB6P]
ME,C(I:2BUABA8<K5F?5H&VXC3G#=*M:/N"4YBWW^UX4^X"3I61IS$E]9L0#C
M]<'AOL#GSL7Y,7+>P:N=P\-W@"='KP_>7)SN[PF,!*/4FB4KI1A,@2:K&N?X
MH:>VZT='11FI0(RS6/7)FKE)0O.HA@<@]YORBA/?\L?M3"LIRRD212\03F2$
M_EO?MD\(;)0S`/C_L->:VV7[)2S26OGJKL=4C\86H\R[TXK%+WSL`$0RJGHX
M%J-@"LW@\V7$F1O%#0!A2F4YD.F-TEE:(1NFEZ)\"J,(983FCI++``:@)00.
MFAH^;6/H<\>W*'3X<ZR2>[F&=K#I/Y^/JW;_*Y5K_R^I$"_GQWO'A+,K-?+!
MW0(>JB(.\+O8OXUD;K$#RY$6YT.HU*A!*N,'K94)HZ*/1-AQ:(/,YB*3V(D*
M4ZLMQ_`,A`WR`9W:(,K2(2LBK?"@^5_PYY#,'E)DE\&SZS51HJD*BC6&'3=A
MBD(V=!TTN\<)QY`X$^,R&E)X/)NKXQG@`;R9,JS:L(XFL"Z=G/#>W=&Q6#-2
M<HW.W>6,SM37MUK\N>T'2\Z4\^6O0*_%1]+<I*Y[1F)CI2U6F9[K55?M;.KF
MB?:)97M+K.9MT3E1Z9;(M"*8_W*CPP^\$Q0R6A73+;'Y^/$F'G:8D$.7JTF;
M?Z:RQ8WN%Z!$JW$/VR7C"=V#`+1AD?[F1#K7-`6TL]791:JH@2N#7P%I[-<J
MNX,@=Q4(H"(.V-,.:FJZLM>>5-J*6B%$`"A:.7P4G0_D-/Y&P`=\@D[Z2K?0
M:@?R6!H%Q*-']HSW*U3&,RY!9SF5!O"$_\C6["AJ5FQNB-]#3=:PU9[O;9.4
MN0,OR?8R6^-P7]@QSQ;;D!05WE!"6IBJX3A7V%)SE/)>C0AF!WPLV2HO4GUD
M([,T<K[DKJ\J=%FEG64ERZ`8=?C.2VKC^`0`+)MTZ78+0>(>GC:)V@!:*YJV
MRMIUYW]C6]%&":'FSDZ>)]..._A`^/#J@T<UU\1W5UB:CW9JX`+04V$6@TH:
M/V6,[+]<A[P7'I!I?Z$F6FP%VM4NZ$<C_!$^K1(@N3W0J-6[,UHZBG)=6<^%
M4T)B>APF6'2N+67[772U`T"UO:?TUM9^$6UMG=3GL]O6#]M5]/GW"30;AN36
MI[8;AL+>=MFPK;<(HB3*`]N$@NM!.IP/R"OIK.K8G3A@%O6L$461.FTOJG%B
M;"\8;#[A`RZN]-I\L.1]+"7AX[[HK'XZXX.L+Y=I1WB_8X:4Z>W<19.VV!;M
MRIBST>Q<.9Z[T6$;_G1F=_3/L_VSLX/CHX.].W<^:E>L?)!ZFL[@L%^6@:$X
M[PY=9T*9.[#H52W$N&F-9-3-_B@G>&LBW!N,;Y3KHT0`/2QP.\6[4R+/$2U<
M^9F:#'@#@?Y&A9@S*)-0B[.SM_:ZD6O0U<WBY<=5%S8QLN8JQR=BH8YM#RH5
MS[!AO(J=[]7GK,]:59-^L:]<-5:=\NR'I^.\^NJ$6/T:]ZJO-VDTNWDS_X>7
MME>";_"VE"XI]6YIJ_*V^(%^8,0M4(-+_V>YC!3*;.3/."%%45:LL4NDRSZ@
M@^+[")Y%.M%0VL)]2>_FGIF?/U>AHK6RX\P=BN.N4-?5(]#H!!E6SA]6L.1?
M_`LM%3H1AGVD[K#.MO[*?M]V:ZB^,6+W$!;6;.$H8QO+#%OX1*)T88OP';7H
MN\Y-JT,%*P025ARF`Y:<F8[Q.6)[X-M!21:%"55I*NVWHB&`O/C^EEIE]UZS
M^]H[]M35EW1KX/$R_ZSRV@R#S00C;%9"=/=8#;2MA?AMB9Q%W)[!;OX3)>!/
M#4!GNZN<?)]1_\PU7.J07!EU?6"`1=,_XY'WD_>GEI^Z,(Q>UZ,;>.0U7Q:7
M?+MS2)1MT,QZY+H.CQ9`8P.ZHUD.*$?Q_:JOK3P,DXK\[-`)6*>8>D]B$9?C
M<5W_^U^C4\T!\]:KNO:XJ>N9(4(\/G*ZDL?MB9"M9"*K.X36JA<[G8NKN,.C
M)2#"W@_4`XL``"INGKF6#8L%R(@:$242,A-U#=F3AAO6\^"##+T:7MN8266I
MY.-L9>H=2-,(^8``DW!:-_B`8I6F^QN[P*THZ5Q%1X::F#Q2E%8^U[CQ^6,I
MMWI2]CM_FUO@0`W2GKU93#J,-6,\S@QU/FO=/;&JHM&-)0)<[0U*:N%]BD=C
MT[5!I,O7X+JWFYM?&@[P1K&QV.:_5S7_R8/B+B5+@DM#=V^KP0$%@D'$98?5
M02(Z<[T1;Z-3">.#4O,7Z5:??.DTZA).]5I6K3DI5@<1EQ6-7O]?9LB]9F[@
MV#Q&95:6VRX!761#0+S;)L8L^E='[IK7LC!R2K4["WOIE/GCV4K0'OB=?2<H
MA2UL;1U;;K:VMBNH17L:*V/:M(&JJ6\3D0VR9'Y=L@)[F9S%32B1+\#1-5M!
M1VB4\9$'Z9+0@K`:]P*2Z1B(<FA]@-<`0T49,PZ1XQY9DD7C]BH'1QK&X*[$
MFEACO`D3%;<`DVYM7*>&;5B1^H,JI,7'=$&1#U[I`G<B@3KJP\7J*J\A50T4
M`4%@7SCATF-(F\_Z*F6?I+8L"8-N#=!),!T6$6P"E]F(M#8@45"1N5K=1^;_
M'T"Z`XKZI($HE3R7Z"U&C.=5B*PN^:MF2H'MT=T=T':=G_'BI7._]?O.X>')
MSLG^Z3;OR>19E@2[AU<4>*ZB:41Y\XJV,=!`3+'_9SYHK5@[W-O?O7@#WY^1
MX+M,LU]=46V/GU<_J#=E(:T$I)V-;@LOM"AW-G#N]@K=B"P13;UR;L@`,BKX
M3C\)"Z#)'U!_RZ^:+S7G=)A1P/P\Q"G1IHIA*PB:Z[]X-$/F6!`F7UU^2Z8$
M@"B<D%60`_'!W@/6>A@QDN17I/&/I=(68.SM7IR)M7<R'';K*@DJF,(IUCD<
MA4,*781%Z$NP40>8D%;8OJXOJ;=7>7#[NG%S<8G\XMG`P&=LT[BN:,7WEN3'
MY%$P]4KCV7M5=P3)MT3%_YT\ERP.)_,BT?'%]1J2D?COP.=;T$&9\^%GP,RY
MHJ59-8F?+6_W_X&:5Q!!(A$X$AY]W[A+"'^-2^[UJ_79_XB0;EY3^)"W?#V!
M='KEBK`K^KZSMW>*GR2P[S"LT_XW#;*S(,!.\[#TR8M'F[,;HS;1<`4T^P_U
>#!)[A=-K7J83LQMN\9V+$`_:/[?^!V3FE&B3-```
`
end
SHAR_EOF
${echo} gunzipping file upgrade_to_8.sh &&

gzip -dc ${lock_dir}/gzi > 'upgrade_to_8.sh' && \
  chmod 0775 'upgrade_to_8.sh'
if test $? -ne 0
then ${echo} "restore of upgrade_to_8.sh failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'upgrade_to_8.sh': 'MD5 check failed'
       ) << \SHAR_EOF
c98e1fb944d6e8acb5eaa86557046aa5  upgrade_to_8.sh
SHAR_EOF

else
test `LC_ALL=C wc -c < 'upgrade_to_8.sh'` -ne 13459 && \
  ${echo} "restoration warning:  size of 'upgrade_to_8.sh' is not 13459"
  fi
# ============= pseudo_orphans.txt ==============
${echo} "x - extracting pseudo_orphans.txt gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh09863/gzi
M'XL("&MLUE,"`W!S975D;U]O<G!H86YS+G1X=`!54KMRW#`,[/45&%_C)*;'
MKRI-QJ6[%/D!B,))T/$5$M19_GI#4G0YSZC@+A9++*@#_!D(CM&Y>.;00T)[
MPIX*E"%6UT%+4%.?L:,.)(*HV*%0$9@H%XX!.*PL9COP1'?-`6@BI8\K_5_5
ML5T:E>4"^B%T\1Q6ZSN]QF(M]*4E5-]2UJ'44O6>2M$A:KH'>(,^RN;D6&=I
M9T@<PA(`G8-,/@KM67;#HCZWOSG\A)BYU[%_??\&*/#X\/`(&#K(=;.XP22F
M)]F3WRS)"Q&<!Y6?<;N4.O73,1'6=7C4_('NFX/2KU#8L\,,;=52S*3]CJSH
MA@!3RE'55RM6RO&VX;&6)1D54I_]-3;7UK%/Q51A5QK'+6IY(./9T\MH1IQ0
M1<IONN<OP'0T+3TV'N.(FWB%3JZ`][HFXU&&YPL[MA^<GBXP=\D(OL<0_6PD
M$UTJ)6B,>8.^>D^Y";9ETSHL\N/Z;!SU:.<EX"Q##"9A1L^GV/S#?ZWC)AN;
@,:@64]E!D>6'R!=8\\03NAV+=7)Z:CX!2VDM>]4"``!A
`
end
SHAR_EOF
${echo} gunzipping file pseudo_orphans.txt &&

gzip -dc ${lock_dir}/gzi > 'pseudo_orphans.txt' && \
  chmod 0664 'pseudo_orphans.txt'
if test $? -ne 0
then ${echo} "restore of pseudo_orphans.txt failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'pseudo_orphans.txt': 'MD5 check failed'
       ) << \SHAR_EOF
3b4e8cae84e139fc3907a4b16cf0713b  pseudo_orphans.txt
SHAR_EOF

else
test `LC_ALL=C wc -c < 'pseudo_orphans.txt'` -ne 725 && \
  ${echo} "restoration warning:  size of 'pseudo_orphans.txt' is not 725"
  fi
# ============= bl_master_package_list.txt ==============
${echo} "x - extracting bl_master_package_list.txt gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh09863/gzi
M'XL("$`?A%4"`V)L7VUA<W1E<E]P86-K86=E7VQI<W0N='AT`&U8VW*L.!)\
MUZ?,!!LQ]L3LQ/Z-$(606S=+HAO\]9LE;J+/>7!3F8"H*M5-EOV:LY!**B.%
M=-$:%;P/)I.04:J)/H1,/?]U0U"B)^D^1&]"9XV?E^[^1L/CG1:I25*(A=*Z
MW/A"SN26R9E<;]<.:SXI91-\5T*P[3.]5(\YWABCN][*7%KN%SS$;C26;B]:
MLY!K""7CYPT6:&YM2PW=9-J%E9USD;='UA(R5FH=,I`?$MAP9T.!3UIBOBD-
M7X3<*CS"*/F&!R^=?>.^U1M1$K4?UC)^*#FVC#7.46JMGV2,Z__,Y[__M"0_
MU>`O%\K<XI@"NUDG,S3T@]9DO&X8.ZNU@4X6@I?RHX38TJHUS5'^GDUI+7$F
MR3?8?::ABPBNV_JA3'.KN$N]7&_1X+(LH_'#S3Z7HTJS5U/+S6].<'-6]J;5
MT]"KP5[U9@OD;OGKK_;&5[2AW7*?AC9U@@JS;^\':W20*<GUMZ2<VP0+CK1T
MLG5HO`=+'*5LEX_3:DV\$_<7DI'NCM_"YMN`:7&Q"IO1,$EF%]I%4Y^[7SR?
MD+`*69S-:.XW2`Z9OALF<QVB0=YR`^1[Z<BH5B6_Y0*'U,W%2#&DZYU([3)%
M]I;*C5B,SY%4":VB!65L'&\?*U1N\5HF0E!WSW];#OIU<?[YN844LV]1569\
MS\B;B7/ND4N/F\,6-;?:_N0:S)&2/:X=0ES$M4RHMTQ5Z1>BMH!?R/Q=EV$W
M(N-11F+NYF)8J_`JAO9+1TO=I8/^.*[-C9<4:NBW(J<F#BR9+;(T"67&8U7%
MY@DUCR/,>0#/L$-M&JM=SUZ+@7HTD1'74<ZV=%_#0PQPEM$>5U706F0R\+T*
MSN%54@A\-#%R4N7ME_QYDV&G0QCX#;*"<D&)]Q\">^(5WGH&._.:E]0AH`TZ
M"$+B*M,L?<F-66I%>*";Z#__%%I:N:Q=IH3&UW'3T4H)30/?'T-"W'BAX5VA
M+3=A[9'=>#S7)CGB!6Z,?X"?:TG12<;)J.RD-NJQP:?Y$5L!GU8DMC"*AD*R
M^V\7[:R-%Z?*'6H_8ISMYRN)+VEK]'V1M>MH$$)?>W?B1MMM?F7Q1V`KP9I^
M'R"0KS9(5&2.MY/&'IF30OA\R:?L^.<=HRFX4-=3_T!^5@D;BYZ?#2MWKL+Y
MS[FJ+Z;'9R^(#$#RHPV=C)/&;F7Y8'*LY64B&(\>DHD61?:WMU\)K>A^N]`"
MG^7G3JQ^$4Z.8Q$U9IW\%MS0'-D!/ZB2_'/%OS,J!6CIB"-='+UL:V45[?,1
M-K!"SL<J7$ML;>YH;GNGVON36Y&KJ*F&4.^:EM1CY_=&A&K@D2F(",Z7!B6J
MR$53'S_D/3\8YCSMT2M"?AE,3J(V&ZB/X"06<O[`;[W#_JF5I]84%EP89C:A
M@O+@JQ-1R\$9_RGVQK2UHX@@18_?RGL,N>A$7(8N\;`R(FNP5").>8PFA:#\
MT;.`.92PQ.IY6KR7/2A=XVV'*NBZX(927!OQHY';(IF5P7-[NTMR@>H)\RNJ
MS';!HNF4^5N[.)7M21-4A_!96]F$$V'L+AB;WC#*`7+K(/%S?'"'"G900F5H
M.;2OPKN4&M)QU[[@ECK-6X6;\(XPN5V`!GTMQ%_#0%CN#`?;G0H<_=)K.K\P
M&=M3*D]S,LCW^;+7W!_G`58>P*'D%Q3I`T<E'6%/AO-QQ`3V7Z%6'9O`[/=3
MVOE$Z9PA=N)G*TX*F)7M)')A.,%`?Y]RI$NTJ'B/`\)O(>8#<;'=UM\@'R:J
M6RK<]G$3C9H2MJ1<A-[LJXA8[RT6*M9U&#H`73SAZ^=;6O,^?)R0T:F+KF/.
MA5H]K>S)\CQ_XE+03$Y(\C+1NLLM-JC1G)^'-<DL=X0PO%1PL\_H-P?T6.J0
M844MSP?F:C%?]K,ES=K1KJ=3L?&EM#"4<("D@@VI3_2Z-B&I&"^9AXT#$`\[
M%\HX,-'IS*1UN+8OZ>LU71[74__9PS)_GA3JZBG7@GJA;VLN&]-+7O<0J:?&
MF$PLY09QJK%'/L]8S3Z\6IGGAQ.?-FTI?ZY;E&U4Y_0JTQ603YPU_`%8M0SW
MM+A,[*.#V8KA)AZ1-G#6;[6/1>/'L(MQ&,4Q]R<.E0F9""D1=R`<K@FFS;[N
M3EZ]$F?F9H7!V8M,LLXO6*#F).)S$[GLXHA11`YC><E$'!&(IM+,AAEEQYL'
M6I0/?D8K#<4,)'+FKHZ^-V*Q@AS'9>[W_UM`'(*`+C(B-<1Y%L"(8#ZJD2RQ
MA;A:\Z2M,1P`&47+[RA,&#A!W+G6"X5/7TARWAD\J2@%S@L>'[FTN"E"1KM3
MO+_,T_9SG#B.<\8BYAY'S_DXE/\A9B[<8O:F8$SE_V1TYYD"[`^Z\Y,LMGF_
M'$/)`6U`O=AD)*]Q!K$MG@@1_'5UFA4OZFW00;Q0IL2+_Z6T?.BPMW(6]_GB
G$KMEGX#%PO.[0%3Q:8V/9\O/?F#@HOV7KAO-1Y__`QNQOL3S$@``
`
end
SHAR_EOF
${echo} gunzipping file bl_master_package_list.txt &&

gzip -dc ${lock_dir}/gzi > 'bl_master_package_list.txt' && \
  chmod 0775 'bl_master_package_list.txt'
if test $? -ne 0
then ${echo} "restore of bl_master_package_list.txt failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'bl_master_package_list.txt': 'MD5 check failed'
       ) << \SHAR_EOF
62100483b5e172e1d04d7ae2b0b4bdb0  bl_master_package_list.txt
SHAR_EOF

else
test `LC_ALL=C wc -c < 'bl_master_package_list.txt'` -ne 4851 && \
  ${echo} "restoration warning:  size of 'bl_master_package_list.txt' is not 4851"
  fi
# ============= message1.txt ==============
${echo} "x - extracting message1.txt gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh09863/gzi
M'XL("%BO_5,"`VUE<W-A9V4Q+G1X=`!=55V/VS80?->OV+>VQEG7I%>@"."'
MY-*B`8K`0"]M\DA3*XDU11+\.)_^?6<IV3[G7DZ6E[,SL[/T;K>C3RYE9:UQ
M`WTP?ON7<>6%?J/=;M<T3Z-)E'0T(=/)6$MF*;ZI]"Y[FGV)-"D]&L<MT=ZR
M2DR154=YY,2-\YD3:16Y+];.=.#>1Y9S%*+7S%W;-!MZ&GGYG!+@9LKJR)3X
MF:.R-*))`OHW'*IT``H@4@?+!!(E\0V1AJ@K492!`Y4P1-6AVG6U;0*<[2I&
MCK.<#_[$D4PFW_>5S;=KV4'I(R!(U-<>G<H*7$`8,F"3LB<UXQ\E:R;2HW(:
MI$:5P4+1P0P7`M8<Y1N<J2(BNPYM7Q.GX@[>YZI+Z`J,\))ZP#FX)7PA?1T(
M/O?13S(KE?5(IJ^2(VL/ZV;Z^,]'>.]^R-2;%R!5=7^J9\#3R<?C]].7>A_I
MR]\?*&4#Y>@V"I/_2@(3![#$=Z02V%0E`*>1;:C.HGCM+$0P3NB8$GFM(?%'
ME<1S,%8'E/RTCOT:-#QUG,S@KB([G@*.N'PGO3VD1:'=I=I.>L?B(`MLSEG)
M9D+>4*TH^E-UT2\3N29!.GFXO3I;HR"#&R0YRLU0Y@;,^%-_.YT1$@[,CH**
MV2B)<PG(`W<7/M)O30ZHG5U:%:I!F:5D>2HN&UN9G:./VF5-M)^"Y>I6S8$P
M6U$ZUA;KE"[I$%J]<2:-ZS(MO/'^^750`I*L!IRKB0%7?LD<'3S;[]_7`[)X
M`^?Z78P^2D\U?[]'D+GNGU96%ROZQ:S5%GD3ZX%'XYR:O).Q'K,/@-,*NYJJ
M*3?[O`8[\H1H+(Z<V8K^4+*\G)9M5#UX5VLOI"`;%Q?]*X[(Z[/JN.!W?KG7
MWM"6]AQQ`V%E_,3`2T9#I#,9GH^LCTO#)-;5V;_?/V$8KC=#P8H9[]KF+5!^
M=ZG$9<^7NH/<>VE.&2PQQ9575?7E@$$7>O/0_OR`TVI+FPVDRJ;?R>2GD,7C
M\P8AT2+A)C.;3?,+NCZN1+C20G%BIMM[.?D^GQ`/-`@^F>RCX=0V#U?.M_57
MG^/KL(@))6RSWTJ^V^97G%]_,>CE[>!KP3JN/R+SYZ^7?8$D?C:^)%F/!*S/
M7^G1&FPQ9D:UPF$SSS.7R[LBZEI#VUJ%OS'G\.[^_F2.II6"UL?AOO/'TH8Q
4X.'DK%?=.W"*N?D?*^[9A-(&``!#
`
end
SHAR_EOF
${echo} gunzipping file message1.txt &&

gzip -dc ${lock_dir}/gzi > 'message1.txt' && \
  chmod 0664 'message1.txt'
if test $? -ne 0
then ${echo} "restore of message1.txt failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'message1.txt': 'MD5 check failed'
       ) << \SHAR_EOF
fd8dc11d1961085385dfc293681dba2a  message1.txt
SHAR_EOF

else
test `LC_ALL=C wc -c < 'message1.txt'` -ne 1746 && \
  ${echo} "restoration warning:  size of 'message1.txt' is not 1746"
  fi
if rm -fr ${lock_dir}
then ${echo} "x - removed lock directory ${lock_dir}."
else ${echo} "x - failed to remove lock directory ${lock_dir}."
     exit 1
fi
exit 0
