---
- hosts: all
  become: yes

  tasks:
    - name: shinken slave configuration file
      template:
        src=slave-shinken-conf.j2
        dest=/etc/shinken/hosts/slaves.cfg
      when: inventory_hostname in groups['local']
      notify: restart shinken

  handlers:
    - name: restart shinken
      service:
        name=shinken
        state=restarted
        enabled=yes

- hosts: slaves
  become: yes

  tasks:
    - apt: update_cache=true upgrade=full

    - name: mandatory packages
      apt: pkg="{{ item }}" state=present
      with_items:
        - ntp
        - snmpd

    - name: mandatory packages
      apt: pkg="ntpdate" state=absent purge=yes

    - name: snmpd config - disable localhost-only listening
      lineinfile:
        name=/etc/snmp/snmpd.conf
        regexp="agentAddress *udp:127.0.0.1:161"
        line="#agentAddress  udp:127.0.0.1:161"
      notify: restart snmpd

    - name: snmpd config - enable any interface listening
      lineinfile:
        name=/etc/snmp/snmpd.conf
        regexp="agentAddress udp:161,udp6:\[::1\]:161"
        line="agentAddress udp:161,udp6:[::1]:161"
      notify: restart snmpd

    - name: snmpd config - setting rocommunity
      lineinfile:
        name=/etc/snmp/snmpd.conf
        regexp=".*rocommunity public *default.*"
        line=" rocommunity public default"
      notify: restart snmpd

    - name: snmpd config - trapsink to shinken server
      lineinfile:
        name=/etc/snmp/snmpd.conf
        regexp="^ trapsink     localhost public"
        line=" trapsink     {{ hostvars['127.0.0.1']['ansible_default_ipv4']['address'] }} public"
      notify: restart snmpd

    - name: adding iburst to ntp config
      replace:
        name=/etc/ntp.conf
        regexp="^server ([0-9\.a-z]*)$"
        replace="server \1 iburst"
      notify: restart ntp

    - name: snmpd && ntp enabled
      service: name="{{ item }}" state=restarted enabled=yes
      with_items:
        - ntp
        - snmpd

  handlers:
    - name: restart snmpd
      service:
        name=snmpd
        state=restarted
        enabled=true

    - name: restart ntp
      service:
        name=ntp
        state=restarted
        enabled=true
