- name: add virtualhost
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/vhost.conf


- name: create cw folder
  file: path=/var/www/cw state=directory mode=775

- name: enable rainloop vhost
  shell: /usr/sbin/php5enmod curl && /usr/sbin/a2enmod ssl && /usr/sbin/a2enmod rewrite && /usr/sbin/a2dissite 000-default default-ssl.conf && /usr/sbin/a2ensite vhost.conf

- name: start apache
  service: name=apache2 state=started


- name: install rainloop
  shell: |
          cd /var/www/cw
          curl -s http://repository.rainloop.net/installer.php | php
          curl -k https://{{ mail_domain }}/?admin
- name: config Rainloop
  file: dest="/var/www/cw/data/_data_/_default_/domains/{{ mail_domain }}.ini" state=touch mode=766


- name: add config your domain in railoop config
  template: src=domain.j2 dest="/var/www/cw/data/_data_/_default_/domains/{{ mail_domain }}.ini"

