- hosts: local
  user: cloud
  sudo: true

  vars:
    wp_db_name: mediawiki


    mediawiki:
      floating_ip: "{{ lookup('file', '/etc/stack_floating_ip') }}"
      password_db: "{{ lookup('password', '/mediawiki/password_db chars=ascii_letters,digits,hexdigits,punctuation') }}"
      secret_key: "{{ lookup('password', '/mediawiki/secret_key length=65 chars=ascii_letters,digits') }}"
      upgrade_key: "{{ lookup('password', '/mediawiki/secret_key length=17 chars=ascii_letters,digits') }}"


  tasks:

    - name: mysql database is created
      mysql_db:
        name=mediawiki
        state=present

    - name: mysql user is created
      mysql_user:
        name=mediawiki
        password="{{ mediawiki.password_db }}"
        priv=*.*:ALL
        state=present
